## SETUP

In [2]:
import math 
import random 
import numpy as np 
import pandas as pd 
import torch 
from torch.utils.data import Dataset, DataLoader
from torch import nn
from sqlalchemy import create_engine

## Fetch data from database

In [181]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [182]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)
num_items = pd.read_sql("SELECT COUNT(*) AS num_items FROM products", engine).iloc[0]['num_items']

In [183]:
df['created_at'] = pd.to_datetime(df['created_at'])

In [184]:
interactions_df = df.rename(columns={'product_id':'item_id','created_at':'timestamp'}).sort_values(['user_id','timestamp']).reset_index(drop=True)

In [185]:
interactions_df.head()

   user_id  item_id           timestamp
0      485      258 2026-04-17 18:15:13
1      485      191 2026-04-17 18:15:13
2      485      192 2026-04-17 18:15:13
3      485      201 2026-04-17 18:15:13
4      485      187 2026-04-17 18:15:13

In [186]:
interactions_df.shape

(10019, 3)

## Mapping handling

In [188]:
interactions_df["real_user_id"] = interactions_df["user_id"] 
interactions_df["user_id"] = interactions_df.groupby("user_id").ngroup() + 1 
interactions_df["real_item_id"] = interactions_df["item_id"]
interactions_df["item_id"] = interactions_df.groupby("item_id").ngroup() + 1

In [190]:
interactions_df.head()

   user_id  item_id           timestamp  real_user_id  real_item_id
0        1      221 2026-04-17 18:15:13           485           258
1        1      176 2026-04-17 18:15:13           485           191
2        1      177 2026-04-17 18:15:13           485           192
3        1      185 2026-04-17 18:15:13           485           201
4        1      172 2026-04-17 18:15:13           485           187

In [191]:
user_id_to_index = dict(zip(interactions_df["real_user_id"], interactions_df["user_id"])) 
item_id_to_index = dict(zip(interactions_df["real_item_id"], interactions_df["item_id"])) 
item_index_to_id = dict(zip(interactions_df["item_id"], interactions_df["real_item_id"]))

In [192]:
user_id_to_index[485],item_id_to_index[191],item_index_to_id[221]

(1, 176, 258)

In [193]:
item_index_to_id[245]

KeyError: 245

## I. CONSTANT VARIABLES FOR SETUP

In [2]:
SEED = 42
NUM_USERS = 1000
NUM_ITEMS = num_items
NUM_CATEGORIES = 10 
MIN_INTERACTIONS = 10 
MAX_INTERACTIONS = 50
MAX_SEQ_LEN = 30
BATCH_SIZE = 64
PAD_ID = 0 
MASK_ID = NUM_ITEMS + 1
VOCAB_SIZE = NUM_ITEMS + 2

NameError: name 'num_items' is not defined

In [195]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

## Turn interactions into sequences

In [198]:
user_sequences = interactions_df.groupby("user_id")["item_id"].apply(list).to_dict()

In [199]:
user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222,
 176]

## Train Test Split

In [200]:
train_user_sequences = {}
test_user_sequences = []
for user_id,seq in user_sequences.items():
    if len(seq) < 2: continue
    train_seq = seq[:-1]
    target_item = seq[-1]

    train_user_sequences[user_id] = train_seq
    test_user_sequences.append({
        "user_id":user_id, 
        "input_sequence": train_seq, 
        "target_item": target_item
    })

In [201]:
train_user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222]

## Create Training Samples For BERT4Rec

In [207]:
training_samples = []

for user_id,sequence in train_user_sequences.items(): 
    for target_index in range(1,len(sequence)): 
        input_sequence = sequence[:target_index+1] 
        
        if len(input_sequence) > MAX_SEQ_LEN: 
            input_sequence = input_sequence[-MAX_SEQ_LEN:]
        
        training_samples.append({"user_id":user_id, "input_sequence": input_sequence})
samples_df = pd.DataFrame(training_samples)

In [208]:
training_samples[1]

{'user_id': 1, 'input_sequence': [221, 176, 177]}

In [209]:
samples_df.head()

   user_id                  input_sequence
0        1                      [221, 176]
1        1                 [221, 176, 177]
2        1            [221, 176, 177, 185]
3        1       [221, 176, 177, 185, 172]
4        1  [221, 176, 177, 185, 172, 194]

## Create mask sequence function

In [210]:
def mask_sequence_for_bert4rec(input_sequence, mask_id,pad_id,mask_prob=0.2): 
    masked_sequence = input_sequence.copy() 
    labels = [-100] * len(input_sequence) 

    candidate_positions =[] 

    for index,item_id in enumerate(input_sequence): 
        if item_id != pad_id : 
            candidate_positions.append(index) 
    masked_any = False 

    for index in candidate_positions: 
        if random.random() < mask_prob: 
            labels[index] = input_sequence[index]
            masked_sequence[index] = mask_id
            masked_any = True 
            
    if not masked_any and len(candidate_positions) > 0:
        index = random.choice(candidate_positions)
        labels[index] = input_sequence[index] 
        masked_sequence[index] = mask_id

    return masked_sequence, labels

## Create Custom Pytorch Dataset

In [211]:
class BERT4RecDataset(Dataset): 
    def __init__(self,samples,max_seq_len,mask_id,pad_id,mask_prob=0.2):
        self.samples = samples 
        self.max_seq_len = max_seq_len 
        self.mask_id = mask_id 
        self.pad_id = pad_id 
        self.mask_prob = mask_prob
    def __len__(self): 
        return len(self.samples)
    def __getitem__(self,index):
        sample = self.samples[index]
        input_sequence = sample["input_sequence"]

        padding_length = self.max_seq_len - len(input_sequence) 
        padded_sequence = [self.pad_id] * padding_length + input_sequence

        masked_sequence, labels = mask_sequence_for_bert4rec(
            input_sequence = padded_sequence,
            mask_id = self.mask_id, 
            pad_id = self.pad_id,
            mask_prob = self.mask_prob
        )

        input_tensor = torch.tensor(masked_sequence,dtype=torch.long)
        target_tensor = torch.tensor(labels,dtype=torch.long)

        return input_tensor,target_tensor
train_dataset = BERT4RecDataset(training_samples,MAX_SEQ_LEN,MASK_ID,PAD_ID,mask_prob=0.2)

In [212]:
input,target = train_dataset[10]
input,target

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 221, 244, 177, 185, 172, 194, 221, 244, 187, 244,
         220, 186]),
 tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100,  176, -100, -100, -100, -100,
         -100,  226, -100,   52, -100, -100]))

## Create DataLoader

In [213]:
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [214]:
input_batch,target_batch = next(iter(train_loader))
print("Input batch shape:",input_batch.shape)
print("Target batch shape:",target_batch.shape)
print("Input first item in batch example:\n",input_batch[0])
print("Target first item in batch example:\n",target_batch[0])

Input batch shape: torch.Size([64, 30])
Target batch shape: torch.Size([64, 30])
Input first item in batch example:
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 244, 244, 185,
        188,  44, 222,  80, 244,  44, 195, 171, 244, 226, 178, 244, 244,  21,
         40, 198])
Target first item in batch example:
 tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,   38,
         196, -100, -100, -100, -100, -100,  220, -100, -100, -100,  195, -100,
        -100,  221,  186, -100, -100, -100])

## Create Class BERT4Rec Model

In [215]:
class BERT4RecModel(nn.Module): 
    def __init__(
            self,
            num_items,
            max_seq_len,
            embedding_dim=64,
            num_attention_heads=2,
            num_transformer_blocks=2,
            dropout_rate=0.1 
        ):
        super().__init__()
        self.num_items = num_items 
        self.max_seq_len = max_seq_len
        self.embedding_dim = embedding_dim

        # 1. Item Embedding Layer
        self.item_embedding = nn.Embedding(
            num_embeddings = VOCAB_SIZE,
            embedding_dim = embedding_dim,
            # Embedding for padding will be a zero vector and not updated during training
            padding_idx = 0 # Position of embedding zero in the embedding matrix
        )

        # 2. Position Embedding Layer
        self.position_embedding = nn.Embedding(
            num_embeddings = max_seq_len, 
            embedding_dim = embedding_dim
        )
        
        self.dropout = nn.Dropout(dropout_rate) # Dropout layer for regularization

        # Transformer Blocks
        transformer_block = nn.TransformerEncoderLayer(
            # Multi-Head Self-Attention
            d_model = embedding_dim,  # Embedding dimension for the transformer, define the dim for matrices Q, K, V
            nhead = num_attention_heads, # Number of attention heads in the multi-head attention mechanism

            # Multi Layer Perceptron (MLP)
            dropout = dropout_rate, # Dropout rate for regularization
            dim_feedforward = embedding_dim * 4, # Expansion Weights 
            activation = "gelu", # Activation function for the feedforward network

            #Supplementary Arguments
            batch_first = True, # Input shape (batch_size, seq_len, embedding_dim)
            norm_first = True # Apply layer normalization before the attention and feedforward layers
        )

        # 3. Transformer Layer
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer = transformer_block, # Base transformer block to be repeated
            num_layers = num_transformer_blocks # Number of transformer blocks
        )
        
        self.layer_norm = nn.LayerNorm(embedding_dim) # Layer normalization to stabilize training 

        # 4. Output Layer
        self.output_layer = nn.Linear(embedding_dim, VOCAB_SIZE) # Linear layer to project
    def forward(self, input_sequences):
        device = input_sequences.device
        batch_size, seq_len = input_sequences.shape 

        positions = torch.arange(
            seq_len, device=device
        )

        positions = positions.unsqueeze(0)
        positions = positions.expand(batch_size, seq_len)

        item_emb = self.item_embedding(input_sequences) 
        pos_emb = self.position_embedding(positions) 

        x = item_emb + pos_emb
        x = self.dropout(x)

        padding_mask = input_sequences.eq(0)

        x = self.transformer_encoder(
            x,
            src_key_padding_mask = padding_mask 
        )

        x = self.layer_norm(x) 
        logits = self.output_layer(x)  

        return logits

## II. CONSTANT VARIABLES FOR TRAINING

In [216]:
EMBEDDING_DIM = 256
NUM_ATTENTION_HEADS = 4
NUM_TRANSFORMER_BLOCKS = 4
DROPOUT_RATE = 0.2
NUM_EPOCHS = 100

## Initialize Bert4Rec Model

In [217]:
model = BERT4RecModel(
    num_items = NUM_ITEMS,
    max_seq_len = MAX_SEQ_LEN,
    embedding_dim = EMBEDDING_DIM,
    num_attention_heads = NUM_ATTENTION_HEADS,
    num_transformer_blocks = NUM_TRANSFORMER_BLOCKS,
    dropout_rate = DROPOUT_RATE
)

/var/folders/v1/f1gz50591kl2_tm8_gxbrtcc0000gn/T/ipykernel_12354/3944191416.py:49: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer_encoder = nn.TransformerEncoder(

## Testing Model with 1 batch

In [222]:
input_batch,target_batch = next(iter(train_loader))

In [223]:
input_batch,target_batch

(tensor([[  0,   0,   0,  ...,  24, 244,  28],
         [  0,   0,   0,  ..., 168, 203, 244],
         [  0,   0,   0,  ..., 126, 127, 244],
         ...,
         [  0,   0,   0,  ..., 244, 244, 195],
         [  0,   0,   0,  ..., 244, 213,  58],
         [  0,   0,   0,  ...,  53,  48,  47]]),
 tensor([[-100, -100, -100,  ..., -100,   17, -100],
         [-100, -100, -100,  ..., -100, -100,   59],
         [-100, -100, -100,  ..., -100, -100,   23],
         ...,
         [-100, -100, -100,  ...,   37,  186, -100],
         [-100, -100, -100,  ...,   58, -100, -100],
         [-100, -100, -100,  ..., -100, -100, -100]]))

In [224]:
input_batch.shape,target_batch.shape

(torch.Size([64, 30]), torch.Size([64, 30]))

In [225]:
logits = model(input_batch)
print("Logits shape:",logits.shape)
print("Logits example:\n",logits)

Logits shape: torch.Size([64, 30, 245])
Logits example:
 tensor([[[ 6.9375e-02, -1.3047e-01,  5.8516e-01,  ...,  9.0013e-01,
          -1.2814e-01,  2.7665e-01],
         [ 8.4515e-02,  3.9224e-03, -6.9680e-02,  ...,  1.6436e-01,
          -7.3298e-01,  1.0044e-01],
         [ 3.3741e-01,  2.3655e-01, -1.3435e-02,  ...,  6.4939e-01,
          -5.0377e-01, -5.2456e-01],
         ...,
         [ 1.5141e+00,  4.1925e-01, -5.5470e-01,  ..., -5.0178e-01,
          -5.6643e-02, -4.8093e-01],
         [ 3.9414e-01,  3.9063e-02, -1.1471e+00,  ...,  9.2293e-01,
          -3.0257e-01, -5.0117e-01],
         [-6.2763e-01,  1.0777e+00, -6.1938e-01,  ..., -1.9116e-01,
          -3.0992e-02,  2.3381e-01]],

        [[ 7.4120e-01,  2.6207e-02,  5.7878e-01,  ...,  7.9900e-01,
          -1.5059e-01, -7.7066e-02],
         [-3.7481e-01,  1.0940e-01, -1.6644e-01,  ..., -3.8879e-01,
           6.2588e-01,  1.9599e-01],
         [ 1.7320e-01, -1.7040e-01,  4.8530e-01,  ...,  3.2567e-02,
          -5.0448e-01, -7.6727e-01],
         ...,
         [ 1.8651e+00,  9.8492e-01,  3.4965e-02,  ...,  7.5623e-02,
           2.5024e-01, -1.2288e+00],
         [ 2.1777e-02,  5.9612e-02,  9.2762e-02,  ...,  5.0686e-01,
           9.5660e-01, -1.6713e-01],
         [-3.4012e-01, -1.2806e-01, -1.3626e+00,  ...,  2.9571e-01,
          -7.0681e-01, -5.0656e-01]],

        [[-1.1447e-01, -6.9837e-02,  7.1114e-02,  ...,  6.2509e-01,
           5.1507e-02,  8.7468e-01],
         [-3.7551e-01, -3.4818e-01, -6.4705e-02,  ..., -8.7574e-01,
           7.1428e-01, -8.4144e-02],
         [-2.3052e-01, -1.3515e-01, -3.8303e-01,  ...,  4.6948e-01,
          -1.4128e-01, -2.0314e-01],
         ...,
         [ 2.9921e+00,  9.3440e-02, -1.0392e+00,  ...,  4.3679e-01,
          -1.5580e+00, -5.0367e-02],
         [ 4.8436e-01, -4.6379e-01, -1.9130e+00,  ...,  5.3854e-01,
           1.0179e-02, -7.9116e-01],
         [-1.6107e-01,  4.4138e-01, -1.4915e+00,  ..., -2.1268e-03,
          -9.0837e-01, -2.2773e-01]],

        ...,

        [[-2.0350e-01, -4.4280e-01,  1.4768e-01,  ...,  7.3639e-01,
          -2.5057e-01,  4.5953e-01],
         [-5.6210e-01, -5.0439e-01,  7.5206e-01,  ..., -6.3882e-01,
           5.1461e-02, -5.2499e-01],
         [-5.5697e-01,  3.9815e-01, -3.0563e-01,  ...,  1.2200e-01,
          -3.4757e-01, -4.2694e-01],
         ...,
         [ 8.7552e-01,  4.6097e-01, -1.2121e+00,  ...,  5.5667e-01,
          -5.5598e-01, -2.8133e-01],
         [ 2.4222e-01, -5.1125e-01, -1.0651e+00,  ...,  5.2984e-01,
          -6.4456e-01, -5.0853e-01],
         [-1.0267e+00,  5.4243e-01, -1.8281e+00,  ...,  6.0011e-01,
           3.2803e-02,  1.1003e-01]],

        [[ 7.2211e-01, -1.2933e-01,  4.1671e-01,  ...,  3.3821e-01,
           6.9575e-01,  5.8438e-01],
         [-7.3052e-01, -1.8776e-01,  1.3710e-01,  ..., -1.0589e+00,
           6.0361e-01,  2.6372e-02],
         [ 4.3682e-01,  3.4471e-01, -3.0650e-01,  ..., -3.1912e-01,
           3.5434e-01, -6.2835e-01],
         ...,
         [ 1.0025e+00,  7.2724e-01, -1.2241e+00,  ..., -1.1052e-02,
           1.3905e-01,  6.9738e-02],
         [-4.7796e-02, -2.9349e-01, -1.5789e+00,  ...,  3.2903e-01,
           7.1041e-01, -7.5152e-01],
         [-1.7976e-01,  1.0711e+00, -1.5351e+00,  ..., -4.0433e-01,
           2.0133e-01, -8.8430e-02]],

        [[-2.5418e-02, -9.0830e-01,  2.5137e-01,  ...,  6.0441e-01,
           3.4716e-01,  4.5567e-01],
         [-7.0129e-01, -6.1015e-01, -5.3622e-01,  ..., -5.3280e-02,
           4.2341e-01,  1.8656e-02],
         [ 2.2100e-01,  2.1656e-01,  1.6566e-02,  ..., -3.9343e-04,
          -4.0389e-02, -3.2362e-01],
         ...,
         [ 1.7346e+00, -5.7296e-01, -6.6170e-01,  ..., -7.6217e-02,
          -2.2200e-02, -6.5112e-01],
         [ 1.5640e+00, -1.2186e-01, -3.4127e-01,  ...,  9.5450e-01,
           2.1933e-01, -9.2771e-01],
         [-7.4935e-01,  6.2080e-01, -1.1072e+00,  ..., -6.8513e-02,
           5.9499e-02,  3.8471e-01]]], grad_fn=<ViewBackward0>)

In [227]:
loss_function = nn.CrossEntropyLoss(ignore_index=-100)
loss = loss_function(logits.view(-1,VOCAB_SIZE),target_batch.view(-1))
print("Loss:",loss.item())

Loss: 5.67335844039917

## Create Training Loop for SASRec

In [228]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu") 
model = model.to(device)

In [229]:
loss_function = nn.CrossEntropyLoss(ignore_index=-100)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

In [230]:
for epoch in range(1,NUM_EPOCHS + 1): 
    model.train()
    total_loss = 0.0
    total_batches = 0

    for input_batch,target_batch in train_loader:
        input_batch = input_batch.to(device) 
        target_batch = target_batch.to(device)

        # ----- Training step -----
        # 1. Feed Forward 
        logits = model(input_batch) 

        # 2. Compute Loss 
        loss = loss_function(logits.view(-1,VOCAB_SIZE),target_batch.view(-1)) 

        # 3. Reset gradients
        optimizer.zero_grad()

        # 4. Feed Backward
        loss.backward()
        
        # 5. Update Weights
        optimizer.step() 
        # -------- Training Step --------

        # Accumulate loss for monitoring 
        total_loss += loss.item()
        total_batches += 1
    avg_loss = total_loss / total_batches
    print(f"Epoch {epoch}/{NUM_EPOCHS}, Average Loss: {avg_loss:.4f}")

Epoch 1/100, Average Loss: 4.5856
Epoch 2/100, Average Loss: 3.9078
Epoch 3/100, Average Loss: 3.8408
Epoch 4/100, Average Loss: 3.7953
Epoch 5/100, Average Loss: 3.7603
Epoch 6/100, Average Loss: 3.7490
Epoch 7/100, Average Loss: 3.7305
Epoch 8/100, Average Loss: 3.7223
Epoch 9/100, Average Loss: 3.7019
Epoch 10/100, Average Loss: 3.6965
Epoch 11/100, Average Loss: 3.6781
Epoch 12/100, Average Loss: 3.6746
Epoch 13/100, Average Loss: 3.6576
Epoch 14/100, Average Loss: 3.6286
Epoch 15/100, Average Loss: 3.6255
Epoch 16/100, Average Loss: 3.6013
Epoch 17/100, Average Loss: 3.5909
Epoch 18/100, Average Loss: 3.5756
Epoch 19/100, Average Loss: 3.5539
Epoch 20/100, Average Loss: 3.5303
Epoch 21/100, Average Loss: 3.5231
Epoch 22/100, Average Loss: 3.4886
Epoch 23/100, Average Loss: 3.4542
Epoch 24/100, Average Loss: 3.4504
Epoch 25/100, Average Loss: 3.4109
Epoch 26/100, Average Loss: 3.3873
Epoch 27/100, Average Loss: 3.3434
Epoch 28/100, Average Loss: 3.3362
Epoch 29/100, Average Loss: 3.2897
Epoch 30/100, Average Loss: 3.2667
Epoch 31/100, Average Loss: 3.2183
Epoch 32/100, Average Loss: 3.1848
Epoch 33/100, Average Loss: 3.1538
Epoch 34/100, Average Loss: 3.1292
Epoch 35/100, Average Loss: 3.0915
Epoch 36/100, Average Loss: 3.0564
Epoch 37/100, Average Loss: 3.0114
Epoch 38/100, Average Loss: 2.9766
Epoch 39/100, Average Loss: 2.9411
Epoch 40/100, Average Loss: 2.9009
Epoch 41/100, Average Loss: 2.8557
Epoch 42/100, Average Loss: 2.8367
Epoch 43/100, Average Loss: 2.7914
Epoch 44/100, Average Loss: 2.7450
Epoch 45/100, Average Loss: 2.7138
Epoch 46/100, Average Loss: 2.6784
Epoch 47/100, Average Loss: 2.6420
Epoch 48/100, Average Loss: 2.6086
Epoch 49/100, Average Loss: 2.5723
Epoch 50/100, Average Loss: 2.5282
Epoch 51/100, Average Loss: 2.5061
Epoch 52/100, Average Loss: 2.4635
Epoch 53/100, Average Loss: 2.4423
Epoch 54/100, Average Loss: 2.3891
Epoch 55/100, Average Loss: 2.3860
Epoch 56/100, Average Loss: 2.3360
Epoch 57/100, Average Loss: 2.3011
Epoch 58/100, Average Loss: 2.2655
Epoch 59/100, Average Loss: 2.2413
Epoch 60/100, Average Loss: 2.2057
Epoch 61/100, Average Loss: 2.1711
Epoch 62/100, Average Loss: 2.1388
Epoch 63/100, Average Loss: 2.1272
Epoch 64/100, Average Loss: 2.0888
Epoch 65/100, Average Loss: 2.0622
Epoch 66/100, Average Loss: 2.0069
Epoch 67/100, Average Loss: 1.9837
Epoch 68/100, Average Loss: 1.9663
Epoch 69/100, Average Loss: 1.9495
Epoch 70/100, Average Loss: 1.9015
Epoch 71/100, Average Loss: 1.8818
Epoch 72/100, Average Loss: 1.8482
Epoch 73/100, Average Loss: 1.8293
Epoch 74/100, Average Loss: 1.8132
Epoch 75/100, Average Loss: 1.7901
Epoch 76/100, Average Loss: 1.7604
Epoch 77/100, Average Loss: 1.7170
Epoch 78/100, Average Loss: 1.7053
Epoch 79/100, Average Loss: 1.6856
Epoch 80/100, Average Loss: 1.6762
Epoch 81/100, Average Loss: 1.6547
Epoch 82/100, Average Loss: 1.6275
Epoch 83/100, Average Loss: 1.5991
Epoch 84/100, Average Loss: 1.5696
Epoch 85/100, Average Loss: 1.5679
Epoch 86/100, Average Loss: 1.5379
Epoch 87/100, Average Loss: 1.4995
Epoch 88/100, Average Loss: 1.5085
Epoch 89/100, Average Loss: 1.5088
Epoch 90/100, Average Loss: 1.4639
Epoch 91/100, Average Loss: 1.4540
Epoch 92/100, Average Loss: 1.4493
Epoch 93/100, Average Loss: 1.4147
Epoch 94/100, Average Loss: 1.4243
Epoch 95/100, Average Loss: 1.3983
Epoch 96/100, Average Loss: 1.3885
Epoch 97/100, Average Loss: 1.3618
Epoch 98/100, Average Loss: 1.3438
Epoch 99/100, Average Loss: 1.3252
Epoch 100/100, Average Loss: 1.3038

## Saving Model

In [268]:
# Save model state_dict
torch.save({"model_state_dict": model.state_dict(),
            "pad_id": int(PAD_ID),
            "mask_id": int(MASK_ID),
            "embedding_dim": int(EMBEDDING_DIM),
            "max_seq_len": int(MAX_SEQ_LEN),
            "num_items": int(NUM_ITEMS),
            "num_attention_heads": int(NUM_ATTENTION_HEADS),
            "num_transformer_blocks": int(NUM_TRANSFORMER_BLOCKS),
            "dropout_rate": float(DROPOUT_RATE), 
            }, "../models/bert4rec/bert4rec_checkpoint.pth")  
# Save mappings
torch.save(user_id_to_index, "../models/bert4rec/user_id_to_index.pth")
torch.save(item_id_to_index, "../models/bert4rec/item_id_to_index.pth")
torch.save(item_index_to_id, "../models/bert4rec/item_index_to_id.pth")

# Save the entire model
torch.save(model, "../models/bert4rec/complete_bert4rec_model.pth")

# ------------------ TESTING ------------------

## Recommend For Next Items

In [233]:
TOP_K = 50

In [241]:
def recommend(model,user_sequence,top_k=TOP_K):
    model.eval() 
    
    if len(user_sequence) > MAX_SEQ_LEN - 1:
        user_sequence = user_sequence[-(MAX_SEQ_LEN-1):]

    sequence_with_mask = user_sequence + [MASK_ID] 
    padding_length = MAX_SEQ_LEN - len(sequence_with_mask)
    padded_sequence = [PAD_ID] * padding_length + sequence_with_mask

    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype=torch.long
    ).to(device)

    with torch.no_grad():
        logits = model(input_tensor) 
        mask_position = len(padded_sequence) - 1 
        scores = logits[0][mask_position] 

    scores[PAD_ID] = float('-inf')
    scores[MASK_ID] = float('-inf')

    for item_id in set(user_sequence): 
        scores[item_id] = float('-inf')
    
    top_scres,top_items = torch.topk(scores, top_k)

    return top_items.cpu().tolist(),top_scres.cpu().tolist(),padded_sequence,logits.cpu().tolist()

In [263]:
index = item_id_to_index[188]

In [264]:
recommended_items,_,padded_seq,_ = recommend(
    model=model,
    user_sequence=[index],
    top_k=10
) 

recommended_items,padded_seq

([197, 194, 195, 174, 222, 59, 175, 221, 212, 187],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  173,
  np.int64(244)])

In [259]:
recommended_items_in_id = [item_index_to_id[item] for item in recommended_items]
recommended_items_in_id

[106, 112, 109, 108, 27, 102, 72, 265, 104, 86]

## Evaluation

In [235]:
def evaluate_model(model,test_samples,top_k=10): 
    hits = []
    recalls = []
    ndcgs = []
    for sample in test_samples:
        user_sequence = sample["input_sequence"]
        target_item = sample["target_item"]
        recommended_items,recommended_scores = recommend(
            model=model,
            user_sequence=user_sequence,
            top_k=top_k
        )

        if target_item in recommended_items: 
            hit = 1
            recall = 1 
            rank = recommended_items.index(target_item) + 1 
            ndcg = 1/math.log2(rank+1) 
        else:
            hit = 0 
            recall = 0 
            ndcg = 0
        hits.append(hit)
        recalls.append(recall)
        ndcgs.append(ndcg)  
    hit_at_k = sum(hits)/len(hits)
    recall_at_k = sum(recalls)/len(recalls)
    ndcg_at_k = sum(ndcgs)/len(ndcgs)

    return hit_at_k, recall_at_k, ndcg_at_k,hits, recalls, ndcgs

In [236]:
hit_at_10, recall_at_10, ndcg_at_10 ,hits, recalls, ndcgs = evaluate_model(model,test_user_sequences,top_k=10)
print(f"Hit@10: {hit_at_10:.4f}, Recall@10: {recall_at_10:.4f}, NDCG@10: {ndcg_at_10:.4f}")

Hit@10: 0.3180, Recall@10: 0.3180, NDCG@10: 0.1444

In [265]:
hits.count(1)

159

In [174]:
len(test_user_sequences)

1000

In [266]:
user_id_to_index[487], item_id_to_index[6], item_index_to_id[1]

(3, 2, 5)