In [6]:
import pandas as pd 
import joblib
df = pd.read_csv("../data/raw_data/products.csv")

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 243 non-null    int64
 1   name               243 non-null    str
 2   brand_name         243 non-null    str
 3   category_name      243 non-null    str
 4   sub_category_name  243 non-null    str
 5   slug               243 non-null    str
 6   thumb_image        243 non-null    str
 7   qty                243 non-null    int64
 8   sku                243 non-null    str
 9   price              243 non-null    int64
 10  offer_price        243 non-null    int64
 11  offer_start_price  243 non-null    str
 12  offer_end_price    243 non-null    str
 13  product_type       243 non-null    str
 14  status             243 non-null    int64
 15  is_approved        243 non-null    int64
 16  short_description  243 non-null    str
 17  long_description   243 non-null    str
 18  seo_title          243 non-null    str
 19  seo_description    243 non-null    str
 20  created_at         243 non-null    str
dtypes: int64(6), str(15)
memory usage: 211.5 KB

In [8]:
# Copy the raw data 
df_raw = df.copy() 
df_clean = df.copy()

In [9]:
# Check shape 
df_clean.shape

(243, 21)

In [10]:
# View first rows 
df_clean.head()

,id,name,brand_name,category_name,sub_category_name,slug,thumb_image,qty,sku,price,...,offer_start_price,offer_end_price,product_type,status,is_approved,short_description,long_description,seo_title,seo_description,created_at
0,5,Nestle Ready Meal Bento Box,Nestle,Grocery & Food,Instant Food,nestle-ready-meal-bento-box,uploads/2026-03-09_1773056017_69aeb0119a74a_ne...,120,NES-GRO-BENTO-001,7,...,2026-03-01,2026-03-18,top,1,1,<b>Instant Food</b><p>Convenient ready meal wi...,<b>Nestle Ready Meal Bento Box</b><p>This read...,Nestle Ready Meal Bento Box,Shop Nestle Ready Meal Bento Box for a quick a...,2024-03-13 11:46:12
1,6,Nike Summer Cotton T-Shirt,Nike,Fashion,T-shirt,nike-summer-cotton-t-shirt,uploads/2026-03-09_1773057158_69aeb486e0a5d_ni...,120,NIK-FAS-TSH-001,25,...,2026-03-02,2026-03-20,featured,1,1,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,<b>Nike Summer Cotton T-Shirt</b><p>This light...,Nike Summer Cotton T-Shirt,Shop Nike Summer Cotton T-Shirt with breathabl...,2024-03-16 09:34:13
2,7,Selons Knit Sweater,Selons,Fashion,Hoodie & Sweater,selons-knit-sweater,uploads/2026-03-09_1773057566_69aeb61e8c1db_se...,90,SEL-FAS-SWT-001,35,...,2026-03-01,2026-03-19,new_arrival,1,1,<b>Knit Sweater</b><p>Soft knit sweater design...,<b>Selons Knit Sweater</b><p>This sweater is m...,Selons Knit Sweater,Shop Selons Knit Sweater with soft fabric and ...,2024-03-16 09:37:00
3,9,Samsung Galaxy Tab S9 5G,Samsung,Mobile Phones,Tablet,samsung-galaxy-tab-s9-5g,uploads/2026-03-09_1773057876_69aeb754dc20d_sa...,35,SAM-MOB-TABS9-001,699,...,2026-03-01,2026-03-18,top,1,1,<b>Tablet</b><p>High performance tablet design...,<b>Samsung Galaxy Tab S9 5G</b><p>This tablet ...,Samsung Galaxy Tab S9 5G,Shop Samsung Galaxy Tab S9 5G for entertainmen...,2024-03-16 09:43:13
4,10,Xiaomi Y68 Smart Watch,Xiaomi,Electronics,Smart Watch,xiaomi-y68-smart-watch,uploads/2026-03-09_1773064221_69aed01d51bc1_xi...,70,XIA-ELE-SMW-001,39,...,2026-03-01,2026-03-20,featured,1,1,<b>Smart Watch</b><p>Affordable smart watch wi...,<b>Xiaomi Y68 Smart Watch</b><p>This smart wat...,Xiaomi Y68 Smart Watch,Shop Xiaomi Y68 Smart Watch with fitness track...,2024-03-16 09:45:28

In [11]:
# View Column names 
df_clean.columns

Index(['id', 'name', 'brand_name', 'category_name', 'sub_category_name',
       'slug', 'thumb_image', 'qty', 'sku', 'price', 'offer_price',
       'offer_start_price', 'offer_end_price', 'product_type', 'status',
       'is_approved', 'short_description', 'long_description', 'seo_title',
       'seo_description', 'created_at'],
      dtype='str')

In [12]:
#Column Rename 
df_clean= df_clean.rename(columns={
    "id":"product_id", 
    "name":"product_name"
})

In [13]:
# Info 
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         243 non-null    int64
 1   product_name       243 non-null    str
 2   brand_name         243 non-null    str
 3   category_name      243 non-null    str
 4   sub_category_name  243 non-null    str
 5   slug               243 non-null    str
 6   thumb_image        243 non-null    str
 7   qty                243 non-null    int64
 8   sku                243 non-null    str
 9   price              243 non-null    int64
 10  offer_price        243 non-null    int64
 11  offer_start_price  243 non-null    str
 12  offer_end_price    243 non-null    str
 13  product_type       243 non-null    str
 14  status             243 non-null    int64
 15  is_approved        243 non-null    int64
 16  short_description  243 non-null    str
 17  long_description   243 non-null    str
 18  seo_title          243 non-null    str
 19  seo_description    243 non-null    str
 20  created_at         243 non-null    str
dtypes: int64(6), str(15)
memory usage: 211.5 KB

In [14]:
# Check Duplicated row: 
df_clean.duplicated().sum()

np.int64(0)

In [15]:
# Check duplicated ID 
df_clean["product_id"].duplicated().sum()

np.int64(0)

In [16]:
# Detect Missing: 
df_clean.isnull().sum()

product_id           0
product_name         0
brand_name           0
category_name        0
sub_category_name    0
slug                 0
thumb_image          0
qty                  0
sku                  0
price                0
offer_price          0
offer_start_price    0
offer_end_price      0
product_type         0
status               0
is_approved          0
short_description    0
long_description     0
seo_title            0
seo_description      0
created_at           0
dtype: int64

In [17]:
# Check data types: 
df_clean.dtypes

product_id           int64
product_name           str
brand_name             str
category_name          str
sub_category_name      str
slug                   str
thumb_image            str
qty                  int64
sku                    str
price                int64
offer_price          int64
offer_start_price      str
offer_end_price        str
product_type           str
status               int64
is_approved          int64
short_description      str
long_description       str
seo_title              str
seo_description        str
created_at             str
dtype: object

In [18]:
# Convert datatype 
categorical_cols= ["brand_name","category_name","sub_category_name","product_type"
                 ,"status","is_approved"] 
datetime_cols = ["offer_start_price","offer_end_price","created_at"]

text_cols = ["product_name",
    "slug",
    "short_description",
    "long_description",
    "sku",
    "seo_title",
    "seo_description"]
for col in datetime_cols: 
    df_clean[col] = pd.to_datetime(df_clean[col]) 
for col in categorical_cols: 
    df_clean[col] = df_clean[col].astype("category") 
for col in text_cols: 
    df_clean[col] = df_clean[col].astype(str).str.strip().str.lower()

In [19]:
# Check text data: 
import re
def remove_html_regex(text): 
    if pd.isna(text): return "Unavailable" 
    clean = re.sub(r"<.*?>", "", text) 
    return clean 
df_clean["short_description"] = df_clean["short_description"].apply(remove_html_regex)
df_clean["long_description"] = df_clean["long_description"].apply(remove_html_regex)
for col in text_cols: 
    df_clean[col] = df_clean[col].str.strip().str.lower().str.replace(r"\s+", " ", regex=True)

In [20]:
#Check category
for col in categorical_cols: 
    print(df_clean[col].unique())

['Nestle', 'Nike', 'Selons', 'Samsung', 'Xiaomi', ..., 'Tefal', 'Disney', 'Pop Mart', 'Funko', 'Hot Toys']
Length: 46
Categories (46, str): ['Acer', 'Adidas', 'Apple', 'Asus', ..., 'Tissot', 'Under Armour', 'Xiaomi', 'YSL Beauty']
['Grocery & Food', 'Fashion', 'Mobile Phones', 'Electronics', 'Computers & Laptops', 'Health & Beauty', 'Watches', 'Toys & Collectibles']
Categories (8, str): ['Computers & Laptops', 'Electronics', 'Fashion', 'Grocery & Food', 'Health & Beauty', 'Mobile Phones', 'Toys & Collectibles', 'Watches']
['Instant Food', 'T-shirt', 'Hoodie & Sweater', 'Tablet', 'Smart Watch', ..., 'Snacks', 'Beverages', 'Laptop', 'Plush Toys', 'Model Figures']
Length: 30
Categories (30, str): ['Battery', 'Beverages', 'Game Disc', 'Gaming console', ..., 'Tablet', 'Trouser', 'Vest & Blazer', 'Women Watch']
['top', 'featured', 'new_arrival', 'best']
Categories (4, str): ['best', 'featured', 'new_arrival', 'top']
[1]
Categories (1, int64): [1]
[1]
Categories (1, int64): [1]

In [21]:
#Export Cleaned data 
df_clean.to_csv("cleaned_products.csv",index=False)

In [22]:
df_clean.to_parquet("cleaned_products.parquet",index=False)

In [23]:
joblib.dump(df_clean,"metadata.joblib")

['metadata.joblib']

In [83]:
first = df_clean.iloc[[1]][["product_id","product_name","category_name","sub_category_name","brand_name","price"
          ,"short_description","long_description"]].T

In [84]:
first.rename(index={"product_id": "Product ID",
                    "product_name": "Name", 
                    "category_name": "Category",
                    "sub_category_name": "Sub-Category", 
                    "brand_name": "Brand", 
                    "price": "Price", 
                    "short_description": "Short Description", 
                    "long_description": "Long Description"}, inplace=True)

In [85]:
first

                                                                   1
Product ID                                                         6
Name                                      nike summer cotton t-shirt
Category                                                     Fashion
Sub-Category                                                 T-shirt
Brand                                                           Nike
Price                                                             25
Short Description  summer t-shirtbreathable cotton t-shirt made f...
Long Description   nike summer cotton t-shirtthis lightweight cot...

In [82]:
df[df_clean["product_name"].str.contains("shirt", case=False, na=False)]

,id,name,brand_name,category_name,sub_category_name,slug,thumb_image,qty,sku,price,...,offer_start_price,offer_end_price,product_type,status,is_approved,short_description,long_description,seo_title,seo_description,created_at
1,6,Nike Summer Cotton T-Shirt,Nike,Fashion,T-shirt,nike-summer-cotton-t-shirt,uploads/2026-03-09_1773057158_69aeb486e0a5d_ni...,120,NIK-FAS-TSH-001,25,...,2026-03-02,2026-03-20,featured,1,1,<b>Summer T-Shirt</b><p>Breathable cotton t-sh...,<b>Nike Summer Cotton T-Shirt</b><p>This light...,Nike Summer Cotton T-Shirt,Shop Nike Summer Cotton T-Shirt with breathabl...,2024-03-16 09:34:13
14,24,Adidas Oversized Graphic T-Shirt,Adidas,Fashion,T-shirt,adidas-oversized-graphic-t-shirt,uploads/2026-03-09_1773066301_69aed83d6f534_ad...,100,ADI-FAS-TSH-002,28,...,2026-03-08,2026-03-30,featured,1,1,<b>Adidas Oversized Graphic T-Shirt</b><p>Mode...,<b>Adidas Oversized Graphic T-Shirt</b> <p>Th...,Adidas Oversized Graphic T-Shirt,Adidas oversized cotton graphic t-shirt design...,2026-03-08 10:37:14
15,25,Adidas Slim Fit Polo Shirt,Adidas,Fashion,Shirt,adidas-slim-fit-polo-shirt,uploads/2026-03-09_1773066446_69aed8cedb5e7_ad...,80,ADI-FAS-POL-003,35,...,2026-03-08,2026-03-30,featured,1,1,<b>Adidas Slim Fit Polo Shirt</b><p>Sporty sli...,<b>Adidas Slim Fit Polo Shirt</b><p>This Adida...,Adidas Slim Fit Polo Shirt,Comfortable slim fit Adidas polo shirt for cas...,2026-03-08 10:44:37
19,29,Under Armour Performance Training T-Shirt,Under Armour,Fashion,T-shirt,under-armour-performance-training-t-shirt,uploads/2026-03-09_1773066900_69aeda940db89_un...,90,UA-FAS-TSH-007,32,...,2026-03-08,2026-03-30,featured,1,1,<b>Under Armour Training T-Shirt</b><p>Perform...,<b>Under Armour Performance Training T-Shirt</...,Under Armour Training T-Shirt,Under Armour athletic performance t-shirt desi...,2026-03-08 11:00:24
20,30,Adidas Streetwear Sweatshirt,Adidas,Fashion,Hoodie & Sweater,adidas-streetwear-sweatshirt,uploads/2026-03-09_1773067055_69aedb2f5f3f9_ad...,85,ADI-FAS-SWT-008,42,...,2026-03-08,2026-03-30,featured,1,1,<b>Adidas Streetwear Sweatshirt</b><p>Soft eve...,<b>Adidas Streetwear Sweatshirt</b><p>This swe...,Adidas Streetwear Sweatshirt,Shop Adidas Streetwear Sweatshirt with soft fa...,2026-03-08 11:23:57
22,32,Nike Sports Polo Shirt,Nike,Fashion,Shirt,nike-sports-polo-shirt,uploads/2026-03-09_1773067294_69aedc1e3c8b3_ni...,75,NIK-FAS-POL-010,38,...,2026-03-08,2026-03-28,featured,1,1,<b>Nike Sports Polo Shirt</b><p>Breathable pol...,<b>Nike Sports Polo Shirt</b><p>This polo shir...,Nike Sports Polo Shirt,Shop Nike Sports Polo Shirt with breathable co...,2026-03-08 11:23:57
27,37,Nike Everyday Crewneck Sweatshirt,Nike,Fashion,Hoodie & Sweater,nike-everyday-crewneck-sweatshirt,uploads/2026-03-09_1773068461_69aee0add2b32_ni...,72,NIK-FAS-SWT-015,40,...,2026-03-08,2026-03-28,top,1,1,<b>Nike Everyday Crewneck Sweatshirt</b><p>Cla...,<b>Nike Everyday Crewneck Sweatshirt</b><p>Thi...,Nike Everyday Crewneck Sweatshirt,Shop Nike Everyday Crewneck Sweatshirt with so...,2026-03-08 11:23:57
28,38,Under Armour Performance Polo Shirt,Under Armour,Fashion,Shirt,under-armour-performance-polo-shirt,uploads/2026-03-09_1773068606_69aee13e65cef_un...,64,UAR-FAS-POL-016,39,...,2026-03-08,2026-03-29,featured,1,1,<b>Under Armour Performance Polo Shirt</b><p>P...,<b>Under Armour Performance Polo Shirt</b><p>T...,Under Armour Performance Polo Shirt,Shop Under Armour Performance Polo Shirt with ...,2026-03-08 11:23:57
31,41,Puma Essential Crew T-Shirt,Puma,Fashion,T-shirt,puma-essential-crew-t-shirt,uploads/2026-03-09_1773068877_69aee24dd2d7e_pu...,105,PUM-FAS-TSH-019,24,...,2026-03-08,2026-03-26,top,1,1,<b>Puma Essential Crew T-Shirt</b><p>Everyday ...,<b>Puma Essential Crew T-Shirt</b><p>This t-sh...,Puma Essential Crew T-Shirt,Shop Puma Essential Crew T-Shirt with soft cot...,2026-03-08 11:23:57

In [79]:
df_clean

,product_id,product_name,brand_name,category_name,sub_category_name,slug,thumb_image,qty,sku,price,...,offer_start_price,offer_end_price,product_type,status,is_approved,short_description,long_description,seo_title,seo_description,created_at
0,5,nestle ready meal bento box,Nestle,Grocery & Food,Instant Food,nestle-ready-meal-bento-box,uploads/2026-03-09_1773056017_69aeb0119a74a_ne...,120,nes-gro-bento-001,7,...,2026-03-01,2026-03-18,top,1,1,instant foodconvenient ready meal with balance...,nestle ready meal bento boxthis ready-to-eat m...,nestle ready meal bento box,shop nestle ready meal bento box for a quick a...,2024-03-13 11:46:12
1,6,nike summer cotton t-shirt,Nike,Fashion,T-shirt,nike-summer-cotton-t-shirt,uploads/2026-03-09_1773057158_69aeb486e0a5d_ni...,120,nik-fas-tsh-001,25,...,2026-03-02,2026-03-20,featured,1,1,summer t-shirtbreathable cotton t-shirt made f...,nike summer cotton t-shirtthis lightweight cot...,nike summer cotton t-shirt,shop nike summer cotton t-shirt with breathabl...,2024-03-16 09:34:13
2,7,selons knit sweater,Selons,Fashion,Hoodie & Sweater,selons-knit-sweater,uploads/2026-03-09_1773057566_69aeb61e8c1db_se...,90,sel-fas-swt-001,35,...,2026-03-01,2026-03-19,new_arrival,1,1,knit sweatersoft knit sweater designed for com...,selons knit sweaterthis sweater is made for co...,selons knit sweater,shop selons knit sweater with soft fabric and ...,2024-03-16 09:37:00
3,9,samsung galaxy tab s9 5g,Samsung,Mobile Phones,Tablet,samsung-galaxy-tab-s9-5g,uploads/2026-03-09_1773057876_69aeb754dc20d_sa...,35,sam-mob-tabs9-001,699,...,2026-03-01,2026-03-18,top,1,1,tablethigh performance tablet designed for ent...,samsung galaxy tab s9 5gthis tablet combines s...,samsung galaxy tab s9 5g,shop samsung galaxy tab s9 5g for entertainmen...,2024-03-16 09:43:13
4,10,xiaomi y68 smart watch,Xiaomi,Electronics,Smart Watch,xiaomi-y68-smart-watch,uploads/2026-03-09_1773064221_69aed01d51bc1_xi...,70,xia-ele-smw-001,39,...,2026-03-01,2026-03-20,featured,1,1,smart watchaffordable smart watch with fitness...,xiaomi y68 smart watchthis smart watch is desi...,xiaomi y68 smart watch,shop xiaomi y68 smart watch with fitness track...,2024-03-16 09:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,287,disney stitch blue plush toy,Disney,Toys & Collectibles,Plush Toys,disney-stitch-blue-plush-toy,uploads/2026-03-14_1773520820_69b5c7b478780_Di...,110,dis-toy-pls-010,28,...,2026-03-08,2026-03-29,featured,1,1,disney stitch blue plush toysoft plush toy ins...,disney stitch blue plush toythis plush toy fea...,disney stitch blue plush toy,buy disney stitch blue plush toy with soft com...,2026-03-14 14:56:59
239,290,pop mart lotso classic figure model,Pop Mart,Toys & Collectibles,Model Figures,pop-mart-lotso-classic-figure-model,uploads/2026-03-14_1773520924_69b5c81c2e294_Po...,85,pop-toy-mod-013,22,...,2026-03-08,2026-03-29,featured,1,1,pop mart lotso classic figure modelcollectible...,pop mart lotso classic figure modelthis model ...,pop mart lotso classic figure model,shop pop mart lotso classic figure model with ...,2026-03-14 14:56:59
240,291,pop mart lotso sitting figure model,Pop Mart,Toys & Collectibles,Model Figures,pop-mart-lotso-sitting-figure-model,uploads/2026-03-14_1773520973_69b5c84de1537_Po...,78,pop-toy-mod-014,24,...,2026-03-08,2026-03-29,top,1,1,pop mart lotso sitting figure modeladorable co...,pop mart lotso sitting figure modelthis collec...,pop mart lotso sitting figure model,buy pop mart lotso sitting figure model with c...,2026-03-14 14:56:59
241,292,funko lotso vinyl figure model,Funko,Toys & Collectibles,Model Figures,funko-lotso-vinyl-figure-model,uploads/2026-03-14_1773521186_69b5c922f1f8d_Fu...,92,fun-toy-mod-015,18,...,2026-03-08,2026-03-29,featured,1,1,funko lotso vinyl figure modelstylized collect...,funko lotso vinyl figure modelthis funko colle...,funko lotso vinyl figure model,shop funko lotso vinyl figure model with styli...,2026-03-14 14:56:59
242,293,pop mart adorable loopy model,Hot Toys,Toys & Collectibles,Model Figures,pop-mart-adorable-loopy-model,uploads/2026-03-14_1773521522_69b5ca7251354_Po...,30,hot-toy-mod-016,289,...,2026-03-08,2026-03-29,best,1,1,pop mart adorable loopy modelcute collectible ...,pop mart adorable loopy modelthis collectible ...,hot toys god of war kratos figure model,buy hot toys god of war kratos figure model wi...,2026-03-14 14:56:59