## Setup

In [161]:
import math 
import random 
import numpy as np 
import pandas as pd 
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
from sqlalchemy import create_engine

## Fetch data from database

In [162]:
DB_URL = "mysql+pymysql://root:123456@127.0.0.1:3306/onlineshop"
engine = create_engine(DB_URL)

In [163]:
df = pd.read_sql(
    """
    SELECT user_id, product_id, created_at
    FROM user_product_interactions
    WHERE user_id IN (
        SELECT id FROM users WHERE name LIKE '%%syn%%'
    )
    """,
    engine
)
num_items = pd.read_sql("SELECT COUNT(*) AS num_items FROM products", engine).iloc[0]['num_items']

In [164]:
df['created_at'] = pd.to_datetime(df['created_at'])

In [165]:
df.head()

   user_id  product_id          created_at
0      485         258 2026-04-17 18:15:13
1      485         191 2026-04-17 18:15:13
2      485         192 2026-04-17 18:15:13
3      485         201 2026-04-17 18:15:13
4      485         187 2026-04-17 18:15:13

In [166]:
interactions_df = df.rename(columns={'product_id':'item_id','created_at':'timestamp'}).sort_values(['user_id','timestamp']).reset_index(drop=True)

In [167]:
interactions_df.head()

   user_id  item_id           timestamp
0      485      258 2026-04-17 18:15:13
1      485      191 2026-04-17 18:15:13
2      485      192 2026-04-17 18:15:13
3      485      201 2026-04-17 18:15:13
4      485      187 2026-04-17 18:15:13

In [168]:
interactions_df.shape

(10019, 3)

## Mapping handling

In [169]:
interactions_df["real_user_id"] = interactions_df["user_id"] 
interactions_df["user_id"] = interactions_df.groupby("user_id").ngroup() + 1 
interactions_df["real_item_id"] = interactions_df["item_id"]
interactions_df["item_id"] = interactions_df.groupby("item_id").ngroup() + 1

In [170]:
interactions_df.head()

   user_id  item_id           timestamp  real_user_id  real_item_id
0        1      221 2026-04-17 18:15:13           485           258
1        1      176 2026-04-17 18:15:13           485           191
2        1      177 2026-04-17 18:15:13           485           192
3        1      185 2026-04-17 18:15:13           485           201
4        1      172 2026-04-17 18:15:13           485           187

In [171]:
user_id_to_index = dict(zip(interactions_df["real_user_id"], interactions_df["user_id"])) 
item_id_to_index = dict(zip(interactions_df["real_item_id"], interactions_df["item_id"])) 
item_index_to_id = dict(zip(interactions_df["item_id"], interactions_df["real_item_id"]))

In [172]:
user_id_to_index[485],item_id_to_index[191],item_index_to_id[221]

(1, 176, 258)

## I. CONSTANT VARIABLES FOR SETUP

In [173]:
SEED = 42 
MAX_SEQ_LEN = 30 
BATCH_SIZE = 64
PAD_ID = 0 
NUM_ITEMS = num_items
VOCAB_SIZE = NUM_ITEMS + 1

In [174]:
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

## Turn interactions into sequences

In [175]:
user_sequences = interactions_df.groupby("user_id")['item_id'].apply(list).to_dict()

In [176]:
user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222,
 176]

## Train test split

In [177]:
train_user_sequences = {}
test_user_sequences = []
for user_id, seq in user_sequences.items():
    if len(seq) < 2 : continue
    train_sequence = seq[:-1]
    target_item = seq[-1]
    train_user_sequences[user_id] = train_sequence
    test_user_sequences.append({
        "user_id": user_id,
        "input_sequence": train_sequence,
        "target_item": target_item
    })

In [178]:
train_user_sequences[1]

[221,
 176,
 177,
 185,
 172,
 194,
 221,
 226,
 187,
 52,
 220,
 186,
 219,
 76,
 187,
 220,
 216,
 171,
 222]

## Create Training Samples FOR SASRec

In [179]:
training_samples = []

for user_id,seq in train_user_sequences.items():
    for target in range(1,len(seq)): 
        input_seq = seq[:target] 
        target_item = seq[target]

        if len(input_seq) > MAX_SEQ_LEN:
            input_seq = input_seq[-MAX_SEQ_LEN:]

        training_samples.append({
            "user_id":user_id,
            "input_sequence":input_seq,
            "target_item":target_item
        })
samples_df = pd.DataFrame(training_samples)

In [180]:
training_samples[1]

{'user_id': 1, 'input_sequence': [221, 176], 'target_item': 177}

In [181]:
samples_df.head()

   user_id             input_sequence  target_item
0        1                      [221]          176
1        1                 [221, 176]          177
2        1            [221, 176, 177]          185
3        1       [221, 176, 177, 185]          172
4        1  [221, 176, 177, 185, 172]          194

## Create Custom Pytorch Dataset

In [182]:
class SASRecDataset(Dataset):
    def __init__(self,samples,max_seq_len,pad_id = 0): 
        self.samples = samples
        self.max_seq_len = max_seq_len
        self.pad_id = pad_id
    def __len__(self):
        return len(self.samples)
    def __getitem__(self,idx):
        sample = self.samples[idx] 
        input_seq = sample["input_sequence"]
        target_item = sample["target_item"]

        padding_length = self.max_seq_len - len(input_seq)
        padded_sequence = [self.pad_id] * padding_length + input_seq

        input_tensor = torch.tensor(padded_sequence,dtype=torch.long)
        target_tensor = torch.tensor(target_item,dtype=torch.long)

        return input_tensor,target_tensor
train_dataset = SASRecDataset(training_samples,MAX_SEQ_LEN,PAD_ID)

In [183]:
input,target = train_dataset[0]
input,target

(tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0, 221]),
 tensor(176))

## Create Dataloader

In [184]:
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [185]:
input_batch,target_batch = next(iter(train_loader))
print("Input batch shape:",input_batch.shape)
print("Target batch shape:",target_batch.shape)
print("Input first item in batch example:\n",input_batch[0])
print("Target first item in batch example:\n",target_batch[0])

Input batch shape: torch.Size([64, 30])
Target batch shape: torch.Size([64])
Input first item in batch example:
 tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38, 196,
        185, 188,  44, 222,  80, 220,  44, 195, 171, 195, 226, 178, 221, 186,
         21,  40])
Target first item in batch example:
 tensor(198)

## Create causal attention mask function

In [186]:
def create_causal_mask(seq_len,device): 
    mask = torch. triu(
        torch.ones(seq_len,seq_len,device = device),
        diagonal = 1
    )
    mask = mask.masked_fill(mask==1,float("-inf"))
    mask = mask.masked_fill(mask==0,float(0.0))
    return mask

In [187]:
create_causal_mask(3,"cpu")

tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])

## Create Class SASRecModel

In [188]:
class SASRecModel(nn.Module):
    def __init__(
        self,
        num_items,
        max_seq_len,
        embedding_dim=64,
        num_attention_heads=2,
        num_transformer_blocks=2,
        dropout_rate=0.1 , 
        pad_id = 0
    ):
        super().__init__()
        self.pad_id = pad_id
        self.num_items = num_items
        self.max_seq_len = max_seq_len
        self.embedding_dim = embedding_dim
        # 1. Item Embedding Layer
        self.item_embedding = nn.Embedding(
            num_embeddings = VOCAB_SIZE, 
            embedding_dim = embedding_dim, 
            padding_idx = 0 # Embedding for padding will be a zero vector and not updated during training
        )
        # 2. Position Embedding Layer
        self.position_embedding = nn.Embedding(
            num_embeddings = max_seq_len,
            embedding_dim = embedding_dim
        )

        self.dropout = nn.Dropout(dropout_rate) # Dropout layer for regularization

        # Transformer Blocks
        transformer_block = nn.TransformerEncoderLayer(
            # Multi-Head Self-Attention
            d_model = embedding_dim,  # Embedding dimension for the transformer, define the dim for matrices Q, K, V
            nhead = num_attention_heads, # Number of attention heads in the multi-head attention mechanism

            # Multi Layer Perceptron (MLP)
            dropout = dropout_rate, # Dropout rate for regularization
            dim_feedforward = embedding_dim * 4, # Expansion Weights 
            activation = "gelu", # Activation function for the feedforward network

            #Supplementary Arguments
            batch_first = True, # Input shape (batch_size, seq_len, embedding_dim)
            norm_first = True # Apply layer normalization before the attention and feedforward layers
        )
        # 3. Transformer Layer
        self.transformer_encoder = nn.TransformerEncoder(
            encoder_layer = transformer_block, # Base transformer block to be repeated
            num_layers = num_transformer_blocks # Number of transformer blocks
        )

        self.layer_norm = nn.LayerNorm(embedding_dim) # Layer normalization to stabilize training

        # 4. Output Layer
        self.output_layer = nn.Linear(
            embedding_dim, # Input dimension from the transformer output
            VOCAB_SIZE # Output dimension equal to vocabulary size
        )
    def forward(self,input_sequences):
        device = input_sequences.device
        batch_size,seq_len = input_sequences.size() 

        positions = torch.arange(seq_len,device=device)
        positions = positions.unsqueeze(0) 
        positions = positions.expand(batch_size,seq_len) 

        item_emb = self.item_embedding(input_sequences) 
        pos_emb = self.position_embedding(positions) 
        
        x = item_emb + pos_emb 
        x = self.dropout(x) 

        # Create causal mask for self-attention to prevent attending to future positions
        causal_mask = create_causal_mask(seq_len, device)

        # Create padding mask to ignore padded positions in the input sequences
        padding_mask_bool = input_sequences.eq(self.pad_id) #[batch_size,seq_len]
        padding_mask = torch.zeros(batch_size, seq_len, device=device, dtype=x.dtype) #[batch_size,seq_len]
        padding_mask = padding_mask.masked_fill(padding_mask_bool, float("-inf"))  #[batch_size,seq_len]

 
        for layer in self.transformer_encoder.layers:
            x = layer(
                x, 
                src_mask=causal_mask, #(seq_len, seq_len) mask for causal attention
                src_key_padding_mask=padding_mask #(batch_size, seq_len) mask for padding positions
            )
            x = torch.nan_to_num(x, nan=0.0)


        x = self.layer_norm(x) 

        # Extract the last hidden state corresponding to the last item in the sequence
        last_hidden_embeddings = x[:,-1,:] 

        # Using the last hidden state to predict the next item in the sequence
        logits = self.output_layer(last_hidden_embeddings) 

        return logits

## II. CONSTANT VARIABLES FOR TRAINING

In [189]:
EMBEDDING_DIM = 256
NUM_ATTENTION_HEADS = 4
NUM_TRANSFORMER_BLOCKS = 4
DROPOUT_RATE = 0.2
NUM_EPOCHS = 100

## Initialize SASRec Model

In [190]:
model = SASRecModel(
    num_items = NUM_ITEMS, 
    max_seq_len = MAX_SEQ_LEN, 
    embedding_dim = EMBEDDING_DIM, 
    num_attention_heads = NUM_ATTENTION_HEADS, 
    num_transformer_blocks = NUM_TRANSFORMER_BLOCKS, 
    dropout_rate = DROPOUT_RATE 
)

/var/folders/v1/f1gz50591kl2_tm8_gxbrtcc0000gn/T/ipykernel_54874/3997828244.py:47: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer_encoder = nn.TransformerEncoder(

## Testing Model with 1 batch

In [191]:
input_batch,target_batch = next(iter(train_loader))

In [192]:
input_batch,target_batch

(tensor([[  0,   0,   0,  ...,   0,  83,  89],
         [  0,   0,   0,  ...,  77, 188, 221],
         [  0,   0,   0,  ...,  19,  29, 123],
         ...,
         [  0,   0,   0,  ..., 141, 123, 115],
         [  0,   0,   0,  ..., 134, 206, 168],
         [  0,   0,   0,  ...,  59, 206, 200]]),
 tensor([ 21,  87, 129, 224,  33, 217, 133, 111, 234, 188, 165, 223,  59,  60,
          65,  51,  61, 179, 188, 171, 229,  52,  11,  51,  27,  29,  50, 162,
         206,  56, 225,  68,  57, 122, 102,  47, 216,  30, 202, 117, 233,  48,
         138,  43,   5,  59, 186,  38, 197, 197,   6,   2, 199, 202,  30, 114,
          13, 170,  95, 204, 198, 128,  46, 194]))

In [193]:
input_batch.shape,target_batch.shape

(torch.Size([64, 30]), torch.Size([64]))

In [194]:
logits = model(input_batch)
print("Logits shape:",logits.shape)
print("Logits example:\n",logits)

Logits shape: torch.Size([64, 244])
Logits example:
 tensor([[-0.2598,  0.2407, -0.2760,  ...,  0.7679,  0.7323,  0.3073],
        [-0.0858,  0.2797, -0.5517,  ...,  0.7105,  0.0356, -0.0732],
        [-0.1595,  0.1486, -0.8667,  ...,  1.0547,  0.4350,  0.1520],
        ...,
        [-0.0232,  0.2797,  0.0344,  ...,  0.1517,  0.9740, -0.1581],
        [ 0.3802,  0.7546, -0.5785,  ...,  0.5099,  1.4334,  0.4550],
        [ 0.5935,  0.3525, -0.7102,  ...,  0.7911,  0.4636,  0.8063]],
       grad_fn=<AddmmBackward0>)

In [195]:
loss_function = nn.CrossEntropyLoss(ignore_index=0) 

# Logits shape: (batch_size, num_items+1), Target shape: (batch_size,)
loss = loss_function(logits,target_batch) 
print("Loss:",loss.item())

Loss: 5.777629375457764

## Create Training Loop for SASRec

In [196]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu") 
model = model.to(device)

In [197]:
loss_function = nn.CrossEntropyLoss(ignore_index=0)
optimizer = torch.optim.Adam(
    model.parameters(),
    lr = 0.001,
    weight_decay = 1e-6
)

In [198]:
for epoch in range(1,NUM_EPOCHS+1):
    model.train() 
    total_loss = 0.0 
    total_batches = 0 
    
    for input_batch,target_batch in train_loader:
        input_batch = input_batch.to(device)
        target_batch = target_batch.to(device) 
        # -------- Training Step --------
        # 1. Feed Forward
        logits = model(input_batch)

        # 2. Compute Loss
        loss = loss_function(logits,target_batch) 
        
        # 3. Reset gradients
        optimizer.zero_grad()

        # 4. Feed Backward
        loss.backward() 

        # 5. Update Parameters 
        optimizer.step()
        # -------- Training Step --------

        # Accumulate loss for monitoring 
        total_loss += loss.item()
        total_batches += 1
        
    avg_loss = total_loss / total_batches
    print(f"Epoch {epoch}/{NUM_EPOCHS}, Average Loss: {avg_loss:.4f}")

Epoch 1/100, Average Loss: 4.7151
Epoch 2/100, Average Loss: 4.0295
Epoch 3/100, Average Loss: 3.8875
Epoch 4/100, Average Loss: 3.8035
Epoch 5/100, Average Loss: 3.7141
Epoch 6/100, Average Loss: 3.6076
Epoch 7/100, Average Loss: 3.5027
Epoch 8/100, Average Loss: 3.3767
Epoch 9/100, Average Loss: 3.2513
Epoch 10/100, Average Loss: 3.1370
Epoch 11/100, Average Loss: 3.0024
Epoch 12/100, Average Loss: 2.8799
Epoch 13/100, Average Loss: 2.7117
Epoch 14/100, Average Loss: 2.5774
Epoch 15/100, Average Loss: 2.4486
Epoch 16/100, Average Loss: 2.3050
Epoch 17/100, Average Loss: 2.1469
Epoch 18/100, Average Loss: 2.0136
Epoch 19/100, Average Loss: 1.8679
Epoch 20/100, Average Loss: 1.7581
Epoch 21/100, Average Loss: 1.6232
Epoch 22/100, Average Loss: 1.5248
Epoch 23/100, Average Loss: 1.4232
Epoch 24/100, Average Loss: 1.3442
Epoch 25/100, Average Loss: 1.2597
Epoch 26/100, Average Loss: 1.1683
Epoch 27/100, Average Loss: 1.0928
Epoch 28/100, Average Loss: 1.0465
Epoch 29/100, Average Loss: 0.9740
Epoch 30/100, Average Loss: 0.9406
Epoch 31/100, Average Loss: 0.8923
Epoch 32/100, Average Loss: 0.8436
Epoch 33/100, Average Loss: 0.8108
Epoch 34/100, Average Loss: 0.7917
Epoch 35/100, Average Loss: 0.7366
Epoch 36/100, Average Loss: 0.7290
Epoch 37/100, Average Loss: 0.6858
Epoch 38/100, Average Loss: 0.6722
Epoch 39/100, Average Loss: 0.6524
Epoch 40/100, Average Loss: 0.6504
Epoch 41/100, Average Loss: 0.6263
Epoch 42/100, Average Loss: 0.6114
Epoch 43/100, Average Loss: 0.5991
Epoch 44/100, Average Loss: 0.5983
Epoch 45/100, Average Loss: 0.5914
Epoch 46/100, Average Loss: 0.5547
Epoch 47/100, Average Loss: 0.5540
Epoch 48/100, Average Loss: 0.5336
Epoch 49/100, Average Loss: 0.5410
Epoch 50/100, Average Loss: 0.5429
Epoch 51/100, Average Loss: 0.5207
Epoch 52/100, Average Loss: 0.5208
Epoch 53/100, Average Loss: 0.5041
Epoch 54/100, Average Loss: 0.4936
Epoch 55/100, Average Loss: 0.4839
Epoch 56/100, Average Loss: 0.4959
Epoch 57/100, Average Loss: 0.4736
Epoch 58/100, Average Loss: 0.4792
Epoch 59/100, Average Loss: 0.4569
Epoch 60/100, Average Loss: 0.4585
Epoch 61/100, Average Loss: 0.4525
Epoch 62/100, Average Loss: 0.4571
Epoch 63/100, Average Loss: 0.4352
Epoch 64/100, Average Loss: 0.4450
Epoch 65/100, Average Loss: 0.4482
Epoch 66/100, Average Loss: 0.4439
Epoch 67/100, Average Loss: 0.4238
Epoch 68/100, Average Loss: 0.4317
Epoch 69/100, Average Loss: 0.4168
Epoch 70/100, Average Loss: 0.4152
Epoch 71/100, Average Loss: 0.4240
Epoch 72/100, Average Loss: 0.3999
Epoch 73/100, Average Loss: 0.4265
Epoch 74/100, Average Loss: 0.4067
Epoch 75/100, Average Loss: 0.4003
Epoch 76/100, Average Loss: 0.3978
Epoch 77/100, Average Loss: 0.4030
Epoch 78/100, Average Loss: 0.3865
Epoch 79/100, Average Loss: 0.3803
Epoch 80/100, Average Loss: 0.3729
Epoch 81/100, Average Loss: 0.3797
Epoch 82/100, Average Loss: 0.3871
Epoch 83/100, Average Loss: 0.3731
Epoch 84/100, Average Loss: 0.3735
Epoch 85/100, Average Loss: 0.3710
Epoch 86/100, Average Loss: 0.3578
Epoch 87/100, Average Loss: 0.3436
Epoch 88/100, Average Loss: 0.3747
Epoch 89/100, Average Loss: 0.3504
Epoch 90/100, Average Loss: 0.3640
Epoch 91/100, Average Loss: 0.3683
Epoch 92/100, Average Loss: 0.3565
Epoch 93/100, Average Loss: 0.3530
Epoch 94/100, Average Loss: 0.3417
Epoch 95/100, Average Loss: 0.3244
Epoch 96/100, Average Loss: 0.3142
Epoch 97/100, Average Loss: 0.3334
Epoch 98/100, Average Loss: 0.3233
Epoch 99/100, Average Loss: 0.3199
Epoch 100/100, Average Loss: 0.3176

In [226]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7795,  0.0642,  0.0860,  ...,  1.1958,  0.6133,  0.1600],
                      [ 1.5584,  0.0131, -0.8033,  ..., -0.3310, -0.9356, -0.6179],
                      ...,
                      [ 1.4869,  0.6814, -0.2091,  ..., -2.2190, -1.2260, -0.2538],
                      [-1.2911,  1.9992,  0.4574,  ..., -0.7450, -1.0046, -0.7227],
                      [-0.3827,  1.5944, -0.7970,  ..., -3.2430, -0.5140, -0.5547]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.7200e-32],
                      ...,
                      [ 6.3086e-01,  1.8103e-01, -1.6471e+00,  ..., -3.0563e-01,
                        8.8985e-01,  1.2663e-02],
                      [ 5.4017e-01,  3.2014e-01, -4.9484e-01,  ..., -4.0792e-01,
                       -4.1240e-02, -9.0508e-01],
                      [ 4.9692e-01,  5.9656e-01, -3.5903e-02,  ...,  6.5206e-01,
                        5.5563e-01, -1.5430e-01]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_weight',
              tensor([[ 0.0064,  0.0921, -0.0565,  ...,  0.1186,  0.1281, -0.0815],
                      [ 0.1670, -0.2681, -0.0433,  ..., -0.2628, -0.1783, -0.0564],
                      [-0.1350, -0.0645, -0.0791,  ..., -0.0943,  0.0144, -0.1401],
                      ...,
                      [ 0.0136, -0.0290, -0.0463,  ..., -0.0168,  0.0104,  0.0740],
                      [ 0.0747, -0.0109, -0.1664,  ..., -0.0085, -0.0540,  0.0829],
                      [-0.0561,  0.0131,  0.1082,  ...,  0.2125, -0.1175,  0.1357]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_bias',
              tensor([ 6.6431e-03,  1.8590e-02,  2.5402e-01, -2.6485e-02,  5.7852e-02,
                      -8.2946e-02,  4.4206e-02,  5.6900e-02,  7.3516e-02,  6.8317e-02,
                       1.2493e-01, -2.6225e-01,  4.4668e-02,  5.0252e-02,  1.3562e-01,
                      -3.6152e-02, -8.2075e-02, -9.8280e-02, -1.4924e-01, -1.1555e-01,
                      -1.3330e-01, -8.5289e-02,  2.7664e-03,  6.0030e-02,  7.6890e-02,
                       1.1247e-01, -8.6968e-02,  7.0134e-02,  4.6705e-02,  1.5839e-02,
                       3.6577e-02,  1.5461e-01,  9.5914e-02, -3.4932e-02,  5.9425e-02,
                      -1.2151e-01, -5.1846e-02,  1.6506e-01,  1.2194e-01, -4.8371e-02,
                      -6.3429e-03, -6.9197e-02,  1.1327e-01, -4.7238e-02,  3.3726e-02,
                      -4.5812e-02, -1.5514e-02, -1.6437e-01, -1.5822e-01,  1.1199e-01,
                       3.4745e-02,  3.1379e-02, -4.4076e-02,  1.7925e-02, -7.9932e-03,
                      -1.0556e-01,  3.9571e-02, -1.3744e-01,  5.9735e-02, -1.2423e-01,
                      -9.3054e-03, -4.7924e-02, -2.1297e-01, -1.0114e-01, -5.7007e-02,
                       9.3563e-02, -1.6699e-01, -1.3224e-01, -1.7985e-01,  2.3028e-01,
                       1.1641e-01,  1.6539e-02, -2.9414e-01, -1.1279e-01,  2.8085e-01,
                       3.6585e-02,  7.1697e-02, -1.4224e-01,  9.9473e-02, -3.3092e-02,
                      -1.7640e-02,  2.1575e-01, -1.4002e-01, -2.2016e-01,  1.1403e-01,
                      -5.3247e-02, -6.6076e-03, -1.2680e-02, -3.3821e-02,  6.2483e-02,
                       2.7996e-02,  7.5133e-03, -1.8384e-01, -3.8965e-02, -1.7766e-01,
                      -2.1348e-02, -2.0718e-01,  6.6428e-02, -7.0877e-02, -1.1955e-01,
                       8.2285e-02,  1.9477e-02, -2.5003e-02, -1.4468e-01,  1.7946e-01,
                       6.6041e-02,  2.8231e-02,  1.6399e-01, -9.4300e-02,  1.3085e-01,
                       1.4066e-02,  1.1889e-01, -1.5489e-01, -4.1116e-02, -1.1144e-02,
                       5.8016e-02, -1.5430e-01,  9.2477e-02, -4.7090e-02, -4.5951e-02,
                       2.5903e-02,  1.0875e-01, -3.2437e-03, -1.1544e-01,  7.6236e-02,
                      -7.8145e-02, -5.9642e-02,  6.0688e-02, -3.2751e-01, -1.0837e-01,
                      -4.1229e-02, -2.5047e-01,  4.6723e-02, -1.4570e-01, -1.0011e-01,
                       2.0646e-01,  1.2510e-01,  6.3165e-02,  9.6769e-02, -5.2077e-02,
                       7.0515e-02, -5.1901e-02,  8.9442e-02, -1.2134e-01,  3.6018e-02,
                       4.4655e-02, -2.8788e-02, -3.9227e-02,  9.6426e-02, -3.8297e-01,
                       2.1033e-01, -3.6272e-02,  2.7055e-01, -1.8653e-02,  1.7402e-02,
                      -8.3565e-02, -2.5585e-01,  1.7288e-01,  7.8483e-02,  1.5699e-01,
                       5.2158e-02, -4.7253e-03, -1.9652e-01, -1.5391e-01, -1.5225e-01,
                      -1.0895e-01,  1.0510e-01, -3.7223e-02,  1.9506e-01, -8.4480e-02,
                       3.3327e-02, -2.6987e-01,  1.8088e-01,  1.6480e-01, -1.1712e-01,
                       6.8231e-02,  7.1807e-02,  6.0608e-02,  1.2583e-01,  1.4426e-01,
                       6.8424e-02, -3.6560e-01,  1.4057e-01,  2.2118e-02,  1.6074e-01,
                      -1.2411e-01, -6.3768e-03,  5.5279e-02, -8.6790e-02,  1.2425e-01,
                      -1.8716e-01,  2.2280e-01,  1.4061e-01,  7.8957e-02,  2.9717e-02,
                      -9.8470e-02,  2.0397e-02,  5.5148e-02, -1.6767e-01, -1.6038e-01,
                       7.4362e-02,  8.8352e-02,  1.1760e-01,  2.4527e-02,  2.3122e-01,
                       4.2277e-02, -2.4659e-01,  1.4459e-03,  2.6857e-01,  1.2097e-01,
                       9.4365e-02, -8.8296e-02,  1.7285e-01, -1.2952e-02,  6.9976e-02,
                       2.4042e-01,  5.2952e-02,  7.0908e-02,  8.6692e-02, -5.3602e-02,
                      -2.3285e-02,  1.2535e-01, -1.9637e-02, -1.5155e-01,  1.6761e-01,
                      -2.9230e-02, -2.8782e-03,  8.9619e-02,  2.3629e-02, -6.0869e-02,
                      -7.1185e-02,  2.6276e-02, -5.9353e-02,  1.7245e-01, -9.4571e-02,
                       6.2425e-02,  3.3974e-02, -9.6658e-02,  1.6621e-01,  5.1490e-02,
                       8.2049e-02, -1.0243e-01,  1.6111e-02, -1.6845e-01, -4.4380e-02,
                       5.5852e-02,  6.8571e-02,  1.6976e-01, -6.5396e-02,  1.7085e-01,
                       1.7114e-01,  2.1300e-01, -8.4574e-03,  1.8087e-01,  1.4193e-01,
                      -7.5187e-02,  2.3297e-05, -9.9859e-05,  1.5445e-04, -6.2449e-05,
                       7.2580e-05, -8.7034e-05, -2.8952e-05,  4.8017e-05,  4.8538e-05,
                       4.2522e-05,  3.9595e-05, -1.5417e-04, -1.9314e-05,  2.4255e-05,
                      -4.2147e-05,  8.3067e-05, -6.0661e-05,  6.1676e-05, -1.4559e-04,
                       1.5981e-04, -3.8827e-05, -5.3849e-05,  2.5643e-06,  3.3424e-05,
                      -2.7575e-05,  2.6600e-06,  8.1566e-05, -2.3981e-05, -9.2065e-05,
                       7.3537e-05,  6.2040e-05, -1.0057e-04, -1.8067e-06,  7.9013e-05,
                      -4.8911e-05, -2.0978e-05, -9.1020e-06, -5.9614e-05, -6.9011e-06,
                      -2.0666e-04,  1.7412e-04,  1.0537e-04, -6.3108e-06, -7.8770e-05,
                      -3.0233e-05,  4.1574e-05,  6.2274e-05, -1.6065e-04, -5.0310e-06,
                       3.0585e-05,  1.0674e-04,  6.3969e-05,  2.5368e-05, -4.1280e-06,
                      -1.5823e-04, -2.0419e-05, -1.5309e-05,  1.2127e-04, -3.5520e-05,
                       3.8001e-05, -2.0576e-06,  2.2629e-05, -3.0141e-05, -7.0873e-05,
                      -7.5094e-05,  3.3664e-05,  1.4800e-05,  1.0638e-04, -5.8768e-05,
                      -1.5223e-04,  1.5719e-05,  5.8617e-05,  2.1977e-05,  2.1677e-06,
                      -4.0169e-05,  8.8567e-05, -3.1258e-05,  1.5294e-05,  7.0415e-05,
                      -9.2942e-07, -2.7400e-05,  1.0962e-04,  8.6501e-05,  1.5616e-05,
                       3.9266e-05, -1.8700e-06, -9.7488e-05,  1.8723e-04, -4.3931e-05,
                      -3.4443e-05,  3.4064e-05, -1.2474e-05, -1.2908e-04,  3.2244e-05,
                       3.0548e-06, -1.6126e-04,  1.3388e-04, -3.9831e-05, -7.3271e-05,
                       1.7937e-04, -1.5357e-05,  2.4118e-06,  3.2233e-05,  2.2574e-05,
                       4.2599e-05, -3.8762e-05, -1.2728e-04, -3.1928e-05, -3.6668e-05,
                      -5.8203e-05,  9.0895e-05,  4.5065e-05, -3.1702e-05,  7.4889e-05,
                      -8.6129e-05, -1.5091e-05,  2.8992e-05, -5.7598e-06,  3.9524e-05,
                      -1.6429e-05, -5.0750e-05, -1.8778e-05,  4.2223e-06,  9.4492e-05,
                      -8.7453e-05,  9.5681e-05,  9.8238e-05,  7.7146e-05,  6.7159e-05,
                       6.3502e-05, -8.7480e-06, -2.9391e-05, -1.5562e-04,  1.4021e-04,
                      -6.9251e-05, -7.9162e-05,  5.1257e-06, -1.2182e-05, -8.8099e-05,
                      -1.9502e-05,  3.0237e-05, -1.0960e-04,  2.1019e-04,  9.0947e-05,
                      -5.9847e-05, -1.2173e-04, -7.1089e-06,  3.8846e-05, -6.4020e-05,
                       1.6518e-05,  3.7573e-05,  8.4671e-05, -1.3243e-04, -1.3113e-04,
                       6.6820e-05,  8.5061e-06,  8.3566e-05,  1.4205e-04,  6.7049e-05,
                       3.9261e-05,  2.8887e-05,  1.7865e-05, -6.0121e-06, -3.3822e-05,
                      -6.7989e-05, -3.2339e-05,  1.9307e-06, -1.2923e-04, -7.5886e-05,
                      -1.5592e-05, -1.7040e-05,  1.7118e-04, -2.6473e-05,  1.6393e-04,
                       1.1859e-06, -2.0758e-05,  4.6217e-05,  5.9667e-05,  5.5728e-05,
                       5.2350e-05,  2.8777e-05, -1.2013e-05, -1.3730e-04,  1.2221e-04,
                      -7.0274e-05,  2.7464e-05,  9.6674e-06,  2.6345e-05, -9.8885e-05,
                      -1.1301e-04, -2.5515e-05, -7.6560e-05, -1.1869e-04,  5.2363e-05,
                       1.4886e-05,  5.4603e-05, -5.6919e-06, -5.4044e-05, -1.6283e-05,
                       1.3170e-04, -1.0557e-04, -2.3929e-05,  1.7495e-04, -6.5930e-05,
                      -1.6587e-05, -1.2393e-04,  1.0113e-05, -2.5379e-05,  3.7191e-06,
                       1.4755e-04, -1.5596e-05,  1.6492e-05, -5.8744e-05, -1.2369e-04,
                      -1.8416e-05, -6.0062e-05, -4.3124e-05, -2.8308e-05,  9.6610e-05,
                      -6.5549e-05, -1.2135e-04,  9.3090e-05,  1.4167e-04,  1.6291e-05,
                       1.8197e-05,  5.3791e-05, -8.9541e-05, -2.9516e-05,  3.2087e-05,
                       6.6578e-05,  1.2900e-04, -4.6354e-05, -9.0688e-05, -1.3036e-04,
                       1.0472e-04,  9.0376e-05, -8.5256e-05,  1.4133e-04, -1.0362e-04,
                      -6.5638e-05, -3.2428e-05, -1.6039e-05,  7.2516e-05,  3.3883e-05,
                       2.7182e-05,  1.9766e-05,  4.1189e-06, -1.8008e-05, -1.4589e-04,
                       6.3808e-05,  1.4216e-04,  4.0054e-05,  8.4648e-06,  7.5112e-06,
                       4.2055e-05, -4.1909e-05, -1.9620e-02,  2.2821e-02, -5.9178e-02,
                       1.1136e-01, -2.6963e-02,  3.4806e-03, -2.3240e-02,  8.2393e-02,
                      -7.8794e-02, -1.2979e-02, -5.6885e-02, -3.1615e-02, -3.4414e-02,
                       7.1995e-02,  3.8072e-04,  3.8823e-02,  2.4930e-02, -1.2184e-01,
                       4.3951e-02,  4.4713e-03, -6.8090e-02, -7.8901e-02, -7.5399e-02,
                       6.5718e-03,  6.8263e-03, -2.4265e-02, -9.0608e-02, -3.6161e-02,
                      -4.5225e-02, -7.4201e-02, -3.9362e-02,  1.2965e-02,  5.5981e-02,
                      -8.4990e-02, -2.8915e-02, -1.6446e-02, -5.3359e-02,  4.4870e-02,
                       3.3111e-02, -6.1977e-02, -1.0785e-01,  5.3130e-03, -2.9047e-02,
                      -7.7593e-02,  2.1266e-02,  1.3932e-02,  4.4028e-02, -2.7190e-03,
                      -3.2514e-03,  8.9403e-03,  7.8265e-02,  4.3603e-02, -6.2694e-02,
                       1.1420e-01,  3.2841e-02,  1.2464e-02, -2.7204e-02, -6.7046e-02,
                       7.6345e-02, -2.0509e-02,  8.3450e-02,  3.4723e-02, -1.9027e-02,
                       4.3572e-02, -5.4079e-02,  3.9466e-02,  4.0653e-02,  1.1909e-01,
                       2.6757e-03, -7.7366e-02,  4.6955e-02, -9.9793e-02,  1.1687e-02,
                      -8.0428e-02, -2.6753e-02,  1.3679e-01,  1.6078e-02,  2.7491e-02,
                       1.3475e-02, -1.5424e-02,  5.3991e-02, -7.3312e-02, -1.9900e-02,
                       8.1849e-02, -1.6306e-02,  8.7072e-03, -1.4120e-02, -7.0064e-02,
                      -3.9838e-02, -5.7975e-02,  5.2260e-02,  3.1655e-02,  5.0774e-02,
                      -1.8694e-02, -6.6119e-02,  2.1104e-02,  5.3867e-02,  5.2951e-02,
                       2.3795e-02,  5.5906e-02,  5.8133e-04, -9.0869e-02, -6.6733e-02,
                      -1.0359e-01, -9.0768e-02,  1.3703e-02, -3.7386e-02,  8.4560e-02,
                      -9.7491e-02,  2.4321e-02, -3.7358e-02,  6.4909e-02,  3.5712e-02,
                       3.4588e-02, -1.2667e-02, -5.2466e-02,  2.6531e-02, -3.3223e-02,
                       1.1681e-02,  1.2268e-01, -3.1269e-02, -5.6970e-04, -2.8038e-02,
                      -3.9526e-02, -4.9130e-02, -7.8550e-03, -2.9122e-02, -5.5762e-02,
                      -2.8771e-03,  7.8072e-03, -5.5797e-02, -4.6947e-02,  6.3587e-02,
                      -4.0360e-02, -4.6541e-02,  1.0773e-01,  4.4696e-02, -7.3606e-02,
                      -3.4312e-02,  9.0236e-03, -1.2680e-01,  5.5229e-02, -5.6996e-02,
                      -1.0262e-02, -1.0607e-01, -5.6076e-03, -9.3149e-02,  7.8357e-02,
                       5.9163e-02, -3.2884e-02,  5.0766e-02, -4.7096e-03,  4.6144e-02,
                       3.9209e-02, -2.0089e-03,  8.3174e-02,  6.3626e-04, -2.9643e-02,
                      -2.1792e-02,  5.5653e-03, -4.3155e-02, -5.3795e-02, -3.8884e-02,
                       1.8212e-02,  8.2759e-02,  1.1959e-01, -2.6254e-03, -1.4701e-03,
                      -3.0351e-03, -2.9818e-02, -1.2298e-01, -6.8112e-02,  6.8170e-02,
                       3.9695e-02, -1.1358e-02,  2.2536e-02, -4.3417e-02, -6.3989e-02,
                       3.6228e-02, -2.3690e-02,  4.3655e-02, -2.0143e-02,  6.8125e-02,
                      -7.6964e-02, -7.8195e-02, -5.5758e-03, -9.6036e-02,  6.5469e-02,
                       7.0229e-02,  4.0930e-02, -1.7226e-02, -3.9139e-02,  4.4687e-02,
                       2.8134e-02, -2.2233e-02, -6.3199e-02,  6.7941e-03,  2.5600e-02,
                       2.1537e-02,  5.4773e-02,  4.0085e-02,  4.1503e-03,  6.8422e-02,
                      -5.6793e-03,  3.4348e-02, -8.0634e-03,  1.2685e-01,  2.7375e-02,
                      -2.0565e-02,  9.2634e-02, -1.0685e-01,  2.4965e-03, -2.5811e-02,
                       1.6992e-02,  6.1862e-02, -4.3866e-02, -3.1789e-03, -1.7862e-02,
                      -8.0865e-02, -1.8768e-02,  5.9707e-03,  4.6281e-02, -1.1403e-02,
                      -8.1978e-03,  2.7390e-03,  8.2202e-02,  5.2634e-02, -5.7383e-02,
                       4.8931e-02,  5.3120e-02, -8.6017e-02,  1.2564e-02,  3.4459e-02,
                      -1.0927e-01,  7.0169e-02,  8.8354e-02,  7.0687e-02,  4.7397e-02,
                      -2.6737e-02, -6.5784e-02,  8.1546e-02, -1.0852e-01,  5.2288e-03,
                      -1.2229e-03,  6.1654e-02, -7.4271e-03, -1.1321e-01,  2.5430e-03,
                       1.0704e-01,  5.6551e-02, -4.5932e-02,  4.1223e-02,  8.8182e-02,
                       5.2187e-02,  3.7069e-03, -6.3054e-02])),
             ('transformer_encoder.layers.0.self_attn.out_proj.weight',
              tensor([[ 0.0236, -0.0367,  0.0273,  ..., -0.0622,  0.0828, -0.0737],
                      [ 0.1898, -0.0233, -0.0207,  ..., -0.0537, -0.0517, -0.0112],
                      [ 0.0342, -0.1297,  0.0636,  ..., -0.0118,  0.0448, -0.0129],
                      ...,
                      [-0.1462, -0.0221, -0.0243,  ..., -0.1800, -0.0147,  0.0410],
                      [ 0.1124,  0.0812, -0.0550,  ...,  0.0180,  0.0322,  0.1443],
                      [ 0.0034, -0.1404,  0.0290,  ...,  0.1786,  0.0656,  0.0869]])),
             ('transformer_encoder.layers.0.self_attn.out_proj.bias',
              tensor([ 0.0581,  0.2009, -0.1252,  0.1416,  0.1152, -0.0142, -0.0244, -0.0956,
                      -0.0634,  0.0928, -0.1092,  0.1491, -0.0020,  0.0997, -0.1203, -0.1177,
                       0.1722, -0.0559,  0.0780, -0.1210,  0.0698, -0.1185,  0.1918,  0.0375,
                       0.0661, -0.0157, -0.0195, -0.1001, -0.0032, -0.0564,  0.1233,  0.1508,
                       0.0019,  0.0399,  0.1488,  0.1133, -0.1018, -0.0153,  0.0233, -0.0591,
                       0.0087, -0.1264,  0.1095, -0.0862,  0.0788,  0.0321, -0.2745,  0.0748,
                      -0.0159,  0.1531, -0.0304, -0.0154,  0.2528,  0.2235,  0.1777,  0.0839,
                      -0.0213,  0.0358, -0.0216,  0.1274,  0.0406,  0.0768, -0.0674,  0.0816,
                      -0.0332,  0.0606,  0.0230,  0.0303, -0.1895,  0.0712,  0.0565,  0.1426,
                      -0.0853, -0.0452,  0.0325, -0.1409, -0.0443,  0.0557, -0.0504,  0.0214,
                      -0.0297,  0.0649, -0.0394, -0.0035,  0.0188, -0.0635,  0.0019, -0.0673,
                       0.0771, -0.0305, -0.0940,  0.0563,  0.0113, -0.0951,  0.0378,  0.2036,
                      -0.0757,  0.0444, -0.1540, -0.0641,  0.1425,  0.1083,  0.1391,  0.0665,
                      -0.0822,  0.0136,  0.0363,  0.0098, -0.0453,  0.1306,  0.0444,  0.0039,
                      -0.3224,  0.1834,  0.0607, -0.1058, -0.1239, -0.1354,  0.2077, -0.0916,
                      -0.0308, -0.0720,  0.1064, -0.0643, -0.0239, -0.1389, -0.1041, -0.1285,
                      -0.1113,  0.0542,  0.0908,  0.1770, -0.0142, -0.1073,  0.1750, -0.1266,
                      -0.0056, -0.0172, -0.0056,  0.1525,  0.0117,  0.2017, -0.0767, -0.1311,
                      -0.0460,  0.1334,  0.1092,  0.0037, -0.2505, -0.0498, -0.1880, -0.0849,
                       0.0843, -0.0500, -0.0050,  0.0546, -0.0477, -0.0154,  0.1698, -0.1324,
                       0.1687,  0.1328, -0.0468,  0.0555, -0.0031, -0.0623, -0.2934,  0.0959,
                       0.1736, -0.0810,  0.1054, -0.1191, -0.0545,  0.0631, -0.1322, -0.0451,
                      -0.0334, -0.1192,  0.0440,  0.0163, -0.0287,  0.0029,  0.0924, -0.0741,
                       0.0946, -0.0094, -0.0275,  0.1415,  0.0842,  0.0133,  0.0475,  0.0044,
                      -0.0374,  0.1817,  0.0577, -0.0140, -0.0118,  0.0224, -0.1220, -0.0606,
                       0.1363, -0.0122, -0.0781, -0.0256,  0.0214, -0.0244, -0.0871, -0.0900,
                      -0.0764,  0.0782, -0.0852, -0.0880, -0.0782,  0.0610, -0.0960,  0.0905,
                      -0.0526,  0.1156, -0.0311,  0.1005, -0.0465, -0.0480,  0.2041,  0.0832,
                      -0.0681, -0.5865,  0.0788, -0.0429,  0.0465, -0.0784, -0.0029, -0.1357,
                      -0.0306, -0.0025, -0.2361, -0.2243, -0.1428,  0.1414,  0.0586, -0.0598,
                      -0.0181, -0.1679, -0.1402, -0.1802, -0.1877,  0.0605, -0.1203,  0.0360,
                      -0.0624,  0.0049,  0.0062,  0.0154,  0.1040,  0.1243, -0.0023,  0.0927])),
             ('transformer_encoder.layers.0.linear1.weight',
              tensor([[-0.0886,  0.0186,  0.1550,  ..., -0.0235, -0.0918, -0.0467],
                      [-0.0494, -0.0749,  0.3088,  ...,  0.3958, -0.2187, -0.0189],
                      [-0.1661,  0.0355,  0.0171,  ..., -0.0695, -0.1012,  0.1139],
                      ...,
                      [-0.0280, -0.0124, -0.0246,  ...,  0.0538,  0.0303, -0.0305],
                      [ 0.0638, -0.3168,  0.0334,  ...,  0.1467,  0.0930, -0.2618],
                      [-0.0482, -0.2649,  0.0152,  ..., -0.1776, -0.0060,  0.1323]])),
             ('transformer_encoder.layers.0.linear1.bias',
              tensor([-0.1720, -0.1802, -0.1611,  ..., -0.1529, -0.1458, -0.2070])),
             ('transformer_encoder.layers.0.linear2.weight',

## Saving Model

In [217]:
# Save model state_dict
torch.save({"model_state_dict": model.state_dict(),
            "pad_id": int(PAD_ID),
            "embedding_dim": int(EMBEDDING_DIM),
            "max_seq_len": int(MAX_SEQ_LEN),
            "num_items": int(NUM_ITEMS),
            "num_attention_heads": int(NUM_ATTENTION_HEADS),
            "num_transformer_blocks": int(NUM_TRANSFORMER_BLOCKS),
            "dropout_rate": float(DROPOUT_RATE),
            }, "../models/sasrec/sasrec_checkpoint.pth")  
# Save mappings
torch.save(user_id_to_index, "../models/sasrec/user_id_to_index.pth")
torch.save(item_id_to_index, "../models/sasrec/item_id_to_index.pth")
torch.save(item_index_to_id, "../models/sasrec/item_index_to_id.pth")

# ------------------ TESTING ------------------

## Recommend for next items

In [218]:
TOP_K = 50

In [219]:
def recommend(model,user_sequence,top_k=10): 
    model.eval()
    if len(user_sequence) > MAX_SEQ_LEN: 
        user_sequence = user_sequence[-MAX_SEQ_LEN:] 
    padding_length = MAX_SEQ_LEN - len(user_sequence)
    padded_sequence = [0] * padding_length + user_sequence

    input_tensor = torch.tensor(
        [padded_sequence], 
        dtype = torch.long
    ).to(device) 

    with torch.no_grad():
        logits = model(input_tensor) 
        scores = logits[0] 
    
    scores[0] = float("-inf")

    for item_id in set(user_sequence): 
        scores[item_id] = float("-inf")
    top_scores,top_items = torch.topk(scores,k=top_k)

    return top_items.cpu().tolist(),top_scores.cpu().tolist()

In [220]:
index = item_id_to_index[188]
index

173

In [221]:
recommended_items = recommend(
    model=model,
    user_sequence=[index],
    top_k=10
) 

recommended_items

RuntimeError: Placeholder storage has not been allocated on MPS device!

In [222]:
recommended_items_id = [item_index_to_id[item_index] for item_index in recommended_items]
recommended_items_id

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [223]:
item_id_to_index[256]

219

In [224]:
logits

tensor([[-4.6058e+00, -1.7574e+00, -5.4354e+00, -4.9104e+00,  1.3899e+00,
          1.7582e+00,  1.7155e+00, -2.0509e+00, -2.4457e+00, -2.7326e+00,
         -3.5659e-01, -1.1363e+00,  2.5655e+00, -4.6306e-01,  3.3002e+00,
         -3.0935e+00, -4.6792e+00,  1.2013e+00, -1.6510e+00,  1.4341e-01,
         -1.4488e+00, -5.1950e+00,  4.1137e+00,  1.9024e-01,  1.0257e+00,
          3.0427e-01, -3.5684e+00, -1.9426e+00,  8.5323e-02,  1.2546e-01,
          1.5202e+00, -3.6988e-01, -1.9189e+00, -1.7962e+00,  9.6615e+00,
         -1.7375e+00, -3.4666e+00,  2.7675e+00, -2.9003e+00, -2.3948e-01,
         -6.2696e+00,  4.7363e+00,  6.1647e-01,  2.9192e+00, -9.3153e+00,
          1.3024e+00,  4.9805e-02,  2.5053e+00,  1.6795e+00,  1.4231e+00,
         -1.2195e+00,  3.1531e+00, -8.7048e-03,  4.1088e+00, -3.7159e-01,
         -9.0866e-02,  1.1639e+00, -2.8051e+00,  3.1199e+00,  1.3377e+00,
          4.6168e+00, -3.3881e+00, -2.9467e+00, -4.8531e-01, -5.4941e+00,
         -5.2388e+00, -4.0803e+00, -1.7414e+00, -2.4402e+00, -4.6545e+00,
         -4.1240e+00, -2.5448e+00, -1.9638e+00, -2.6979e+00, -6.5713e+00,
         -4.2665e+00, -3.3490e+00, -4.3014e+00, -4.7809e+00, -3.3460e-01,
         -2.4492e+00, -8.0772e+00,  1.0307e-01, -4.5410e+00,  2.4891e+00,
         -2.2153e+00,  3.9741e-01,  1.1855e+00, -2.0889e+00, -4.8397e+00,
         -2.1876e-01, -2.8355e+00, -5.3183e-02,  3.5747e-01, -4.7790e-01,
         -3.1716e-01,  9.9839e-03, -9.7549e-01, -1.6192e+00,  7.9014e-01,
          1.7595e+00, -3.7013e-01,  3.1725e+00, -4.3195e+00,  1.1932e+00,
         -6.5971e+00, -1.3510e-01, -3.2248e+00, -4.5342e+00,  6.7327e-01,
         -9.5688e-01, -2.2245e+00,  2.1036e+00, -4.5454e+00, -1.5146e+00,
         -4.5450e+00, -5.2605e+00, -2.1270e+00, -2.7017e+00, -4.7401e-01,
         -3.9099e+00,  1.0188e-01,  2.6612e+00, -7.7124e-01, -1.8172e+00,
         -3.3941e+00, -2.2914e+00,  5.8914e-01,  1.9457e-01, -2.9967e+00,
         -2.4540e+00, -4.4078e-01, -5.1271e+00, -3.9661e+00, -6.0915e+00,
         -2.9168e+00, -5.4556e+00, -4.5268e+00, -1.6896e+00, -6.3333e-01,
          3.1245e-01, -3.1856e+00, -4.0965e+00,  1.8516e+00,  4.2220e+00,
         -4.4687e+00,  2.2682e+00, -2.9978e+00, -4.1324e+00, -4.5830e+00,
          2.5235e+00, -4.8719e+00,  9.5970e-01, -1.0923e+00, -2.1746e-02,
         -3.0118e+00, -2.4210e+00, -5.0341e-01, -3.3887e+00, -4.5662e+00,
         -3.5119e+00, -8.5929e-01,  4.2453e-01, -2.3236e-01, -1.8360e+00,
         -5.2355e+00, -2.2409e+00, -4.3322e+00, -3.4719e+00, -2.7109e+00,
         -5.8992e-01, -2.5545e+00, -3.6680e+00, -1.6890e+00, -4.5527e+00,
         -2.9595e+00, -1.1362e+00, -2.3795e+00, -1.7053e+00,  1.1189e+01,
          4.1064e+00,  9.2250e+00,  3.0497e+00,  4.9196e+00,  2.1679e-01,
         -3.8839e+00, -8.4288e+00, -3.3674e+00, -3.1968e+00,  4.0454e+00,
          4.3326e+00,  1.5681e+00,  4.3899e+00,  6.6461e+00, -3.5520e+00,
         -3.5396e+00,  2.1270e+00, -5.0636e-01, -6.0846e-01,  5.2802e+00,
          3.5920e+00,  3.9490e+00,  4.6830e+00,  4.1342e+00,  2.9966e+00,
          2.8234e+00,  1.3310e+00,  3.1781e+00,  1.0124e+00, -6.9088e-01,
         -2.2524e+00,  6.4141e-01,  1.5389e+00, -3.2596e-01, -3.0101e+00,
         -2.4842e+00,  4.2352e+00,  1.5452e+00,  7.6610e-01, -2.3348e+00,
          5.8897e-01, -3.6951e+00, -2.2747e+00,  7.6444e-02, -1.6428e+00,
         -3.0386e+00, -5.4945e+00, -6.4662e+00, -5.5704e+00, -7.3804e+00,
         -1.6075e+00, -2.8150e+00, -1.2587e+00,  5.6925e-01,  4.8941e-01,
         -2.6980e+00,  3.3123e-01, -2.4106e+00,  1.8742e-01,  9.9116e-01,
         -3.4951e+00, -6.0445e-01, -2.7770e+00, -5.2870e+00]])

## Evaluation

In [225]:
def evaluate_model(model,test_samples,top_k=10): 
    hits = []
    recalls = []
    ndcgs = []
    for sample in test_samples:
        user_sequence = sample["input_sequence"]
        target_item = sample["target_item"]
        recommended_items,recommended_scores = recommend(
            model=model,
            user_sequence=user_sequence,
            top_k=top_k
        )

        if target_item in recommended_items: 
            hit = 1
            recall = 1 
            rank = recommended_items.index(target_item) + 1 
            ndcg = 1/math.log2(rank+1) 
        else:
            hit = 0 
            recall = 0 
            ndcg = 0
        hits.append(hit)
        recalls.append(recall)
        ndcgs.append(ndcg)  
    hit_at_k = sum(hits)/len(hits)
    recall_at_k = sum(recalls)/len(recalls)
    ndcg_at_k = sum(ndcgs)/len(ndcgs)

    return hit_at_k, recall_at_k, ndcg_at_k, hits, recalls, ndcgs

In [ ]:
hit_at_10, recall_at_10, ndcg_at_10 ,hits, recalls, ndcgs = evaluate_model(model,test_user_sequences,top_k=10)
print(f"Hit@10: {hit_at_10:.4f}, Recall@10: {recall_at_10:.4f}, NDCG@10: {ndcg_at_10:.4f}")

Hit@10: 0.2080, Recall@10: 0.2080, NDCG@10: 0.1080

In [ ]:
hits.count(1)

84

In [ ]:
len(test_user_sequences)

500

In [ ]:
len(train_user_sequences)

500

## PLAYAROUND

In [ ]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7052,  0.2038,  0.0638,  ...,  1.4430,  0.6490,  0.2800],
                      [ 1.5394,  0.0817, -0.8138,  ..., -0.0685, -0.8470, -0.6226],
                      ...,
                      [ 1.6393,  0.6826, -0.4277,  ..., -2.2997, -0.9771, -0.2916],
                      [-1.5357,  1.8551,  0.5394,  ..., -0.6225, -1.0055, -0.3962],
                      [-0.2480,  1.7671, -0.8074,  ..., -3.1909, -0.4274, -0.5168]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.7200e-32],
                      ...,
                      [ 5.8179e-01,  2.3182e-01, -1.5956e+00,  ..., -2.7562e-01,
                        7.6769e-01,  5.7620e-02],
                      [ 3.7739e-01,  3.0346e-01, -4.4730e-01,  ..., -1.5544e-01,
                       -3.0836e-02, -1.0839e+00],
                      [ 4.8959e-01,  5.1534e-01, -4.0893e-02,  ...,  6.9522e-01,
                        4.7759e-01, -6.4484e-02]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_weight',
              tensor([[ 0.0249,  0.0718, -0.0114,  ..., -0.0531,  0.0034, -0.1256],
                      [ 0.1641, -0.1847, -0.0898,  ..., -0.0482, -0.1629, -0.0391],
                      [-0.0032, -0.0318, -0.1858,  ..., -0.1287, -0.1343,  0.0453],
                      ...,
                      [-0.0809,  0.0773,  0.0189,  ...,  0.0733,  0.0738,  0.0457],
                      [ 0.0665, -0.0688, -0.0749,  ...,  0.0824, -0.1030, -0.0041],
                      [-0.0210,  0.0779, -0.0029,  ...,  0.1190, -0.0990,  0.2418]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_bias',
              tensor([ 9.3268e-02, -5.2520e-02,  7.4719e-02,  6.3096e-02,  8.1962e-02,
                      -1.6513e-01,  8.4651e-02,  1.1230e-01,  1.1863e-01, -4.7002e-04,
                       4.9549e-03, -1.4116e-01,  3.0130e-02,  2.3155e-01, -5.5066e-03,
                       6.1870e-02, -7.9237e-02,  1.0291e-01,  4.4762e-02, -2.7218e-01,
                      -5.0574e-02, -6.8799e-02,  1.8778e-01,  4.6059e-03,  1.5136e-01,
                       3.4899e-02, -1.1075e-01,  6.3713e-02, -5.1837e-02, -7.1066e-02,
                      -8.8103e-02, -3.1828e-02,  4.7336e-02, -1.0676e-02, -1.7552e-02,
                       1.2617e-01,  2.5054e-03, -1.1913e-01, -8.1183e-02,  1.1888e-02,
                      -1.6748e-01, -8.7096e-02,  1.0743e-01,  5.6140e-03,  5.6044e-02,
                      -6.5247e-02, -6.9837e-02, -1.8602e-01, -1.0442e-01,  8.1333e-02,
                       2.2510e-02, -4.1458e-02, -2.7047e-02, -4.3601e-02,  4.2354e-02,
                      -9.1031e-02, -1.0890e-02, -2.7816e-02,  1.2303e-01, -2.0267e-01,
                       4.2186e-03, -6.6783e-02, -2.1265e-01,  9.9077e-03, -3.0956e-02,
                       1.8989e-01, -2.4954e-01, -8.3687e-02, -1.4828e-01,  1.0124e-01,
                       4.6575e-02, -4.9220e-02, -2.3434e-01, -2.0624e-02,  8.4412e-02,
                      -8.2837e-02,  3.6233e-02, -2.6586e-01,  3.2329e-02, -7.8906e-02,
                      -3.5900e-03,  2.3260e-01, -2.7169e-02, -3.1248e-01, -4.7452e-02,
                       9.7073e-02, -4.9833e-02, -2.3643e-01, -6.4636e-02,  9.4662e-02,
                       4.6315e-02, -1.3189e-01, -4.9071e-02, -2.1861e-01, -6.6831e-02,
                      -8.1857e-02, -1.5992e-01,  3.8980e-02, -2.6008e-02, -1.5652e-01,
                       1.6030e-01, -1.5435e-01, -1.6482e-01, -1.7073e-01,  1.3926e-01,
                       1.3839e-01, -1.5395e-01,  1.0745e-01, -1.0130e-01,  1.3645e-01,
                       7.2577e-02,  2.1719e-02, -1.9305e-01, -8.5153e-02,  3.4146e-02,
                       1.9276e-01, -1.3529e-01,  8.0546e-02,  5.7112e-02, -9.3170e-02,
                       1.2141e-01,  1.5308e-01, -3.3165e-02, -4.7156e-03,  1.3372e-01,
                      -1.2269e-01, -2.4445e-01,  5.0074e-02, -2.2520e-01, -1.0836e-01,
                      -1.0974e-01, -6.2154e-02,  4.1906e-02, -1.3498e-01, -1.9594e-01,
                       2.3101e-01,  1.2844e-01,  1.0759e-04, -8.5479e-02, -5.2053e-02,
                       1.5307e-01, -1.8710e-01,  2.5637e-02, -4.7522e-02,  1.3760e-01,
                      -2.7382e-03, -4.7516e-02, -4.9277e-02,  8.4360e-02, -2.3369e-01,
                       8.0772e-02,  5.4968e-02,  1.2583e-01,  7.5824e-02, -6.0740e-02,
                      -3.3749e-02, -1.4861e-01,  1.6681e-01,  1.5914e-01,  4.3362e-02,
                       5.9586e-02,  7.6273e-03, -4.7664e-02, -1.6491e-01,  2.5190e-02,
                      -1.6746e-01,  1.6350e-02, -5.5894e-02,  1.5433e-01, -3.8004e-02,
                       8.4089e-02, -1.2947e-01, -1.5294e-02,  2.5104e-01,  1.0837e-02,
                       1.6297e-01, -9.0540e-03,  1.1117e-01,  1.3519e-02,  1.2420e-01,
                       1.1614e-01, -1.4456e-01,  1.5888e-01,  3.4107e-02,  5.4846e-02,
                      -1.9706e-01, -2.0373e-02, -1.2181e-02, -3.6733e-02, -3.2378e-02,
                      -1.0044e-01,  4.1445e-02, -9.1914e-03, -9.2482e-02,  9.2388e-02,
                       2.7036e-02, -1.3218e-01,  5.4225e-02, -1.2652e-01, -5.8205e-02,
                       1.9587e-02,  2.9823e-02,  1.4830e-01, -1.4617e-01,  4.7651e-02,
                       1.2668e-02, -2.5927e-01,  1.2965e-01,  2.0607e-01,  4.3316e-02,
                      -1.6788e-02, -2.1685e-03,  1.7624e-01, -1.2514e-01, -7.5947e-02,
                       2.0452e-01,  9.5196e-02, -1.2130e-02,  1.1974e-01, -1.0124e-01,
                       2.2189e-02,  2.7174e-01,  8.2888e-02, -2.5757e-01,  3.8890e-02,
                      -7.1611e-03, -2.2683e-02,  1.2003e-01, -1.2379e-01,  1.9626e-02,
                      -1.0858e-01, -1.6866e-01, -1.4802e-01,  1.8492e-01, -1.8777e-02,
                       7.5064e-02, -5.0577e-02, -1.0832e-01,  3.9524e-03,  6.8115e-02,
                       4.5683e-02,  1.1157e-02, -5.4119e-02, -1.0052e-01, -5.0542e-02,
                       1.4660e-01,  1.5267e-01,  2.0814e-01, -3.9378e-02,  1.8517e-01,
                       2.4842e-01,  2.9646e-01,  8.9807e-02,  1.2412e-01,  2.1696e-01,
                      -9.6523e-02,  2.1647e-05, -3.6673e-05, -3.5228e-04,  5.8752e-06,
                      -3.8657e-05,  1.2290e-04, -6.9372e-05,  1.2062e-06,  6.6383e-05,
                       2.8495e-05, -1.0121e-04,  6.5478e-05, -1.2234e-04, -1.4971e-04,
                      -3.0282e-05, -7.3591e-05, -8.8374e-05,  1.1106e-04,  3.2191e-05,
                      -3.1743e-04,  4.9658e-05, -7.0496e-05, -5.3131e-05,  1.2581e-04,
                      -7.7090e-05,  3.3194e-05, -1.4683e-04,  1.7605e-04,  5.3779e-05,
                      -3.2564e-05,  8.8859e-05, -7.6906e-05, -9.4952e-05, -1.0071e-04,
                       2.9890e-05,  1.0206e-04,  4.0123e-05,  8.3178e-05,  5.4068e-05,
                       4.1020e-05, -8.5973e-05, -1.2364e-04, -1.8362e-05, -6.4710e-05,
                      -3.0124e-05, -4.6270e-07, -1.7151e-04,  7.3650e-05,  5.4833e-05,
                      -2.8047e-05, -1.6436e-04,  9.4869e-05, -1.7607e-04,  4.1573e-05,
                       2.3508e-05,  2.4667e-05,  4.5808e-05, -1.0155e-04, -1.6620e-05,
                       4.6119e-05,  4.9967e-06, -4.3291e-05, -1.1411e-04, -3.8139e-05,
                       6.7480e-05,  6.3438e-05,  5.6340e-05,  1.0092e-04,  2.4402e-05,
                      -5.1888e-05, -1.0046e-04, -2.4961e-05,  4.7676e-05,  1.8520e-05,
                      -1.1171e-04,  1.2705e-04,  1.1986e-05,  8.5586e-05, -4.7854e-05,
                      -1.2370e-05, -1.1449e-04,  2.0438e-05, -7.8692e-07,  3.0475e-05,
                       7.8357e-05,  1.4210e-05,  6.0861e-05,  4.6428e-05,  8.9862e-07,
                      -2.1794e-05,  4.9135e-05,  8.4939e-05,  5.2244e-05,  2.1973e-05,
                      -1.7017e-05,  1.8920e-05, -3.0629e-05,  3.8517e-05,  2.9613e-05,
                      -3.9123e-05, -5.6070e-05, -6.4077e-06,  9.0594e-05,  9.0582e-06,
                      -1.4654e-04, -6.4330e-05, -6.1190e-05, -4.2460e-05,  8.8985e-05,
                       3.2046e-05,  6.3735e-06,  9.9369e-06,  2.6840e-05, -3.5555e-06,
                       3.1770e-05, -1.2322e-04,  4.1270e-05,  5.4916e-05, -4.6144e-05,
                       7.0094e-05, -2.4979e-05, -7.0892e-05, -2.9978e-05,  1.1779e-04,
                       1.0383e-04,  1.8297e-04,  3.0914e-05, -1.8054e-04, -3.5678e-05,
                       5.9306e-06,  1.4125e-04,  8.0257e-05,  5.0492e-06, -1.6448e-04,
                       1.9952e-04,  4.4272e-05, -1.6984e-05,  1.5918e-05, -2.4804e-05,
                       4.2135e-05, -2.1970e-05,  1.0906e-05, -3.5321e-06, -1.7556e-05,
                      -4.7590e-05, -2.8289e-05, -1.2385e-04, -8.1788e-06,  9.8410e-05,
                       1.2017e-04, -4.0177e-05, -4.0977e-05, -1.4117e-05, -7.3033e-05,
                       6.6055e-05,  3.3290e-05,  2.8921e-05,  6.6409e-05, -6.7481e-05,
                       1.0315e-05, -9.0912e-05,  6.9566e-06, -6.3490e-05, -7.7423e-05,
                      -5.9141e-06, -3.1891e-05,  3.7854e-06,  6.6653e-05, -4.0099e-05,
                       2.7990e-05,  5.0863e-05,  1.2491e-04, -2.9000e-06,  7.9076e-05,
                       5.5404e-05, -3.5717e-05,  4.4728e-05, -1.2393e-04,  8.8344e-05,
                      -7.9128e-05,  3.2385e-05,  7.1912e-05, -1.6006e-04,  2.8924e-05,
                       9.2723e-06,  1.8558e-05,  1.4966e-05,  1.9496e-08, -1.3460e-04,
                       8.6982e-05, -9.5471e-05,  1.8593e-05,  2.1015e-05, -7.8140e-05,
                      -3.8695e-05, -9.7317e-05, -1.6095e-05,  1.2267e-05, -1.6002e-04,
                       1.8296e-04,  5.0589e-06, -6.6398e-05, -9.1906e-05, -2.2370e-05,
                       4.7423e-05, -4.8282e-05,  1.3673e-05,  2.1209e-05,  2.1406e-05,
                       5.9914e-05, -1.2935e-05, -1.6655e-05,  1.3430e-06, -1.3737e-05,
                       1.5860e-04,  1.0658e-04, -2.8273e-04, -1.6526e-05,  1.2511e-04,
                       1.5318e-04,  7.4507e-05,  5.9887e-05,  3.7631e-05, -3.4440e-05,
                       1.3593e-04,  9.4463e-05,  4.2068e-05,  6.5760e-05, -1.8003e-05,
                       4.4540e-05, -1.6659e-04, -9.0759e-06,  1.5011e-04,  6.3709e-05,
                       1.0530e-04,  9.2522e-05,  1.2929e-05,  3.2906e-05,  9.8895e-05,
                       4.0001e-05,  4.9669e-05, -1.8805e-05,  6.6631e-05,  1.0329e-04,
                       1.5398e-04,  2.0750e-06,  2.6539e-05, -1.3154e-05, -1.0353e-04,
                       2.9963e-05,  7.3028e-05,  4.3613e-05,  2.4359e-05, -1.1454e-04,
                       1.6899e-04, -2.7171e-05,  1.8245e-02,  3.3797e-02,  5.3302e-02,
                       1.4224e-01, -5.0618e-02,  1.9983e-02, -1.2830e-02,  4.8929e-02,
                      -1.0607e-01,  8.4200e-02, -6.9892e-02,  8.2900e-03, -3.9575e-02,
                       5.8729e-02, -2.7500e-02,  2.9351e-02,  5.9504e-02, -1.3100e-01,
                       4.1513e-02, -2.3515e-02, -7.1441e-02, -3.4607e-02, -8.1740e-02,
                      -3.6799e-02,  3.4999e-03, -4.3576e-02, -8.4887e-02,  2.8317e-03,
                       2.4562e-02, -6.1376e-02, -3.3903e-02,  2.8024e-02,  1.4616e-02,
                      -1.3585e-02,  1.0479e-02,  5.3815e-03, -7.7213e-02,  8.6872e-02,
                       5.2923e-02, -9.7526e-02, -1.0576e-01,  6.2163e-02, -5.6375e-02,
                      -9.5754e-02,  3.3429e-02, -4.5850e-04,  6.9571e-02,  7.3451e-03,
                       4.8286e-03, -4.3161e-02,  1.1530e-01,  9.0787e-02, -3.5082e-02,
                       9.2603e-02, -3.0412e-02, -1.6017e-02, -4.6035e-02, -6.4826e-03,
                       9.9787e-04, -4.5533e-02,  3.4952e-02,  6.0684e-02,  3.5327e-02,
                      -3.8772e-03,  1.9560e-02,  5.0682e-02,  1.7208e-02,  7.6974e-02,
                      -4.2162e-02, -8.3312e-02,  1.2740e-02, -3.7246e-02, -6.4429e-02,
                      -4.9311e-02, -4.0816e-02,  1.1026e-01, -9.6740e-03,  8.2816e-02,
                       6.3534e-02,  3.3280e-03, -3.7726e-02, -5.5071e-02, -1.9876e-02,
                       4.9246e-02, -5.1981e-02,  7.3670e-02,  1.4801e-02, -2.3301e-02,
                       2.9774e-02,  3.3126e-02,  4.0303e-02,  5.3743e-02,  6.0518e-02,
                       5.5711e-03, -4.1191e-02,  3.7644e-02,  1.8993e-02,  2.8518e-02,
                       2.2556e-02,  8.3411e-02, -3.1471e-02, -5.2919e-02, -9.0958e-02,
                      -7.0168e-02, -7.3483e-02,  9.6303e-02, -1.6255e-03,  9.4687e-03,
                      -1.2863e-01, -1.9106e-02,  7.2935e-03,  5.8735e-02,  2.1489e-02,
                      -7.4805e-03,  1.5371e-02,  1.2493e-02,  2.2929e-02, -2.8191e-02,
                      -3.0670e-02,  9.9198e-02, -1.3019e-02, -1.9684e-05, -8.3468e-02,
                      -5.4268e-02,  1.4779e-02, -1.7697e-02, -6.8725e-02,  1.1436e-02,
                      -1.3931e-02,  1.6104e-02, -4.2671e-02, -9.1879e-02,  6.9584e-03,
                      -1.9788e-02, -4.7332e-02,  7.1774e-02,  4.5377e-02, -1.7741e-02,
                      -5.5170e-02,  4.8911e-02, -1.0427e-01,  5.2292e-02, -1.6376e-02,
                       1.6466e-02, -8.6153e-02, -4.7611e-02, -2.4292e-02,  1.2580e-02,
                       6.5162e-02,  4.3400e-03,  8.3687e-02,  5.4813e-02,  2.2390e-02,
                       4.2195e-02, -1.1019e-02,  1.4452e-01, -3.2060e-02, -3.7128e-02,
                      -1.5055e-02,  2.1531e-02, -2.9275e-02, -1.7462e-02, -1.3388e-02,
                       1.4557e-02,  3.1413e-03,  1.2570e-01, -3.0488e-02, -3.2269e-02,
                       3.8136e-02,  3.2652e-02, -1.0406e-01, -3.5863e-02,  7.5790e-03,
                       6.4388e-02, -5.6310e-03,  2.7990e-02,  3.1629e-02, -4.3699e-02,
                       2.9506e-03,  4.1133e-03, -3.9094e-02,  1.4639e-02,  8.9126e-04,
                      -4.2408e-02, -8.8587e-02,  1.8589e-02, -1.1137e-01, -7.4037e-03,
                       5.9343e-02,  1.9781e-02, -4.8874e-03,  5.0408e-03,  7.2484e-03,
                       2.3910e-02, -5.3915e-02, -3.6713e-02, -2.3776e-02,  6.6704e-02,
                      -5.7817e-03,  3.9266e-02,  8.2008e-02,  1.5993e-02,  1.1464e-01,
                       3.4142e-02, -6.7226e-04, -3.6732e-02,  3.7429e-02, -1.4584e-03,
                      -4.9780e-02,  1.1320e-01, -6.9337e-02, -4.4407e-02,  9.7938e-04,
                       2.3457e-02, -5.7772e-03,  3.1709e-02, -2.3197e-02, -4.2027e-02,
                       2.6105e-02, -4.0477e-02,  4.5248e-02,  3.9675e-02, -4.6204e-02,
                       3.4772e-03, -8.9226e-03,  1.2128e-01,  1.3656e-03,  1.3435e-02,
                      -2.4840e-04,  8.0865e-02, -7.8186e-02,  4.2668e-02, -1.1825e-02,
                      -7.8995e-02,  5.2106e-02,  1.4258e-02,  1.2253e-01, -7.7842e-03,
                       4.2940e-03, -1.2865e-02,  4.8557e-02, -4.1897e-02,  7.3753e-02,
                      -4.7189e-02,  5.2869e-02,  5.3771e-02, -1.4080e-01, -2.4200e-02,
                       1.3257e-02,  3.5188e-02, -3.3268e-02,  4.4330e-02,  7.0767e-02,
                      -5.6885e-02,  3.9898e-02, -1.2277e-01])),
             ('transformer_encoder.layers.0.self_attn.out_proj.weight',
              tensor([[ 0.0035,  0.0460,  0.0875,  ..., -0.0336,  0.0821, -0.0909],
                      [ 0.1025, -0.0022, -0.0442,  ...,  0.0692, -0.0109,  0.0256],
                      [-0.0428,  0.0203,  0.0092,  ..., -0.0317, -0.0495,  0.0144],
                      ...,
                      [-0.1559,  0.1309, -0.0039,  ..., -0.2294,  0.0144,  0.0261],
                      [-0.0222, -0.0963,  0.0838,  ...,  0.0721, -0.0894,  0.1477],
                      [-0.0713, -0.0365, -0.0562,  ...,  0.1312,  0.0410,  0.0773]])),
             ('transformer_encoder.layers.0.self_attn.out_proj.bias',
              tensor([ 0.0221,  0.1419, -0.1103,  0.1334,  0.1670,  0.0477, -0.0633, -0.0683,
                      -0.0583,  0.1092, -0.0197,  0.1455, -0.0371,  0.0437, -0.1454, -0.0463,
                       0.1796, -0.0807,  0.0644, -0.0989,  0.0764, -0.1662,  0.2582,  0.0607,
                       0.0573, -0.0857, -0.0271, -0.1168, -0.0154, -0.0583,  0.0070,  0.1541,
                       0.0399,  0.0440,  0.1308,  0.1337, -0.1119,  0.0302, -0.0370,  0.0408,
                      -0.0829, -0.1503,  0.0660, -0.1305,  0.1196,  0.0638, -0.2892,  0.1118,
                       0.0698,  0.1976,  0.0634, -0.0030,  0.2140,  0.2132,  0.1952,  0.0810,
                      -0.0364,  0.0503,  0.0503,  0.1308,  0.0392,  0.1184, -0.0312,  0.0224,
                      -0.0782,  0.0470, -0.0175, -0.0246, -0.1517,  0.0594, -0.0066,  0.1923,
                      -0.1229, -0.0204, -0.0030, -0.1065, -0.0967,  0.0619, -0.0173,  0.0269,
                      -0.0243,  0.0553, -0.0041,  0.0070, -0.0057, -0.1082, -0.0098, -0.1364,
                      -0.0192, -0.0086, -0.1014,  0.0829,  0.0040, -0.0322, -0.0835,  0.2139,
                      -0.1114,  0.0809, -0.1441, -0.0272,  0.2193,  0.1532,  0.1698,  0.0535,
                      -0.0789,  0.0526,  0.0121, -0.0664, -0.1159,  0.1766,  0.0280, -0.0066,
                      -0.2570,  0.1889,  0.0229, -0.1484, -0.0465, -0.1651,  0.1799, -0.0547,
                      -0.0609, -0.0816,  0.0721, -0.0517, -0.0133, -0.0972, -0.1083, -0.1269,
                      -0.1029,  0.0570,  0.0535,  0.2359,  0.0075, -0.1182,  0.1191, -0.0941,
                      -0.0571,  0.0529,  0.0055,  0.0517,  0.0206,  0.1562, -0.1083, -0.0516,
                      -0.0858,  0.1920,  0.0714, -0.0362, -0.2634, -0.1007, -0.1235, -0.0690,
                       0.0483, -0.0849, -0.0445,  0.0542, -0.0569, -0.0108,  0.0992, -0.1388,
                       0.1460,  0.0986, -0.0715,  0.0248,  0.0035, -0.1408, -0.2397,  0.1111,
                       0.1667, -0.0716,  0.0957, -0.1196, -0.0417,  0.1372, -0.0978, -0.0083,
                      -0.0445, -0.1504, -0.0158,  0.0296, -0.0517,  0.0308,  0.0974, -0.0604,
                       0.0588,  0.0189, -0.0409,  0.1156,  0.1138, -0.0202,  0.0748, -0.0082,
                      -0.0547,  0.1537,  0.0859, -0.0558, -0.0698,  0.0700, -0.1061, -0.1131,
                       0.1056, -0.0761, -0.0384, -0.0336,  0.0608, -0.0435, -0.0262, -0.0561,
                      -0.1213,  0.1242, -0.1619, -0.2170, -0.0772,  0.0987, -0.0181,  0.0625,
                      -0.1378,  0.1680, -0.0630,  0.0909,  0.0315,  0.1111,  0.2209,  0.0937,
                      -0.0423, -0.6413,  0.1266, -0.0404,  0.0009,  0.0056, -0.0258, -0.1878,
                      -0.0164,  0.0317, -0.1650, -0.2853, -0.1489,  0.1065,  0.1102, -0.0392,
                      -0.0406, -0.1651, -0.1777, -0.1841, -0.1712,  0.0756, -0.1497,  0.0092,
                      -0.0331,  0.0089, -0.0445,  0.0266,  0.0937,  0.0475,  0.0242,  0.1194])),
             ('transformer_encoder.layers.0.linear1.weight',
              tensor([[-0.3254, -0.1375,  0.1430,  ..., -0.0111, -0.0753,  0.0755],
                      [-0.0952, -0.0563,  0.1685,  ...,  0.2234,  0.0636, -0.1738],
                      [-0.0890, -0.1458, -0.1798,  ..., -0.2079, -0.3324, -0.0127],
                      ...,
                      [-0.1135, -0.0278,  0.1261,  ..., -0.1463,  0.1472, -0.1250],
                      [-0.1384, -0.2681,  0.0802,  ...,  0.1231, -0.0472, -0.1576],
                      [-0.0717, -0.1335, -0.0989,  ..., -0.1968, -0.1289,  0.0295]])),
             ('transformer_encoder.layers.0.linear1.bias',
              tensor([-0.1916, -0.1190, -0.1407,  ..., -0.1642, -0.1109, -0.1851])),
             ('transformer_encoder.layers.0.linear2.weight',

In [ ]:
user_id_to_index[487], item_id_to_index[6], item_index_to_id[1]

(3, 2, 5)

In [215]:
model.state_dict()

OrderedDict([('item_embedding.weight',
              tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
                      [-1.7795,  0.0642,  0.0860,  ...,  1.1958,  0.6133,  0.1600],
                      [ 1.5584,  0.0131, -0.8033,  ..., -0.3310, -0.9356, -0.6179],
                      ...,
                      [ 1.4869,  0.6814, -0.2091,  ..., -2.2190, -1.2260, -0.2538],
                      [-1.2911,  1.9992,  0.4574,  ..., -0.7450, -1.0046, -0.7227],
                      [-0.3827,  1.5944, -0.7970,  ..., -3.2430, -0.5140, -0.5547]])),
             ('position_embedding.weight',
              tensor([[-1.0003e-31,  9.4428e-32,  1.0142e-31,  ...,  1.0253e-31,
                        9.8931e-32, -1.0783e-31],
                      [ 1.0460e-31,  9.9900e-32,  9.4717e-32,  ...,  1.0345e-31,
                       -9.7955e-32, -9.9962e-32],
                      [-1.0135e-31, -1.0074e-31,  1.0369e-31,  ..., -1.0177e-31,
                        1.0016e-31,  9.7200e-32],
                      ...,
                      [ 6.3086e-01,  1.8103e-01, -1.6471e+00,  ..., -3.0563e-01,
                        8.8985e-01,  1.2663e-02],
                      [ 5.4017e-01,  3.2014e-01, -4.9484e-01,  ..., -4.0792e-01,
                       -4.1240e-02, -9.0508e-01],
                      [ 4.9692e-01,  5.9656e-01, -3.5903e-02,  ...,  6.5206e-01,
                        5.5563e-01, -1.5430e-01]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_weight',
              tensor([[ 0.0064,  0.0921, -0.0565,  ...,  0.1186,  0.1281, -0.0815],
                      [ 0.1670, -0.2681, -0.0433,  ..., -0.2628, -0.1783, -0.0564],
                      [-0.1350, -0.0645, -0.0791,  ..., -0.0943,  0.0144, -0.1401],
                      ...,
                      [ 0.0136, -0.0290, -0.0463,  ..., -0.0168,  0.0104,  0.0740],
                      [ 0.0747, -0.0109, -0.1664,  ..., -0.0085, -0.0540,  0.0829],
                      [-0.0561,  0.0131,  0.1082,  ...,  0.2125, -0.1175,  0.1357]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_bias',
              tensor([ 6.6431e-03,  1.8590e-02,  2.5402e-01, -2.6485e-02,  5.7852e-02,
                      -8.2946e-02,  4.4206e-02,  5.6900e-02,  7.3516e-02,  6.8317e-02,
                       1.2493e-01, -2.6225e-01,  4.4668e-02,  5.0252e-02,  1.3562e-01,
                      -3.6152e-02, -8.2075e-02, -9.8280e-02, -1.4924e-01, -1.1555e-01,
                      -1.3330e-01, -8.5289e-02,  2.7664e-03,  6.0030e-02,  7.6890e-02,
                       1.1247e-01, -8.6968e-02,  7.0134e-02,  4.6705e-02,  1.5839e-02,
                       3.6577e-02,  1.5461e-01,  9.5914e-02, -3.4932e-02,  5.9425e-02,
                      -1.2151e-01, -5.1846e-02,  1.6506e-01,  1.2194e-01, -4.8371e-02,
                      -6.3429e-03, -6.9197e-02,  1.1327e-01, -4.7238e-02,  3.3726e-02,
                      -4.5812e-02, -1.5514e-02, -1.6437e-01, -1.5822e-01,  1.1199e-01,
                       3.4745e-02,  3.1379e-02, -4.4076e-02,  1.7925e-02, -7.9932e-03,
                      -1.0556e-01,  3.9571e-02, -1.3744e-01,  5.9735e-02, -1.2423e-01,
                      -9.3054e-03, -4.7924e-02, -2.1297e-01, -1.0114e-01, -5.7007e-02,
                       9.3563e-02, -1.6699e-01, -1.3224e-01, -1.7985e-01,  2.3028e-01,
                       1.1641e-01,  1.6539e-02, -2.9414e-01, -1.1279e-01,  2.8085e-01,
                       3.6585e-02,  7.1697e-02, -1.4224e-01,  9.9473e-02, -3.3092e-02,
                      -1.7640e-02,  2.1575e-01, -1.4002e-01, -2.2016e-01,  1.1403e-01,
                      -5.3247e-02, -6.6076e-03, -1.2680e-02, -3.3821e-02,  6.2483e-02,
                       2.7996e-02,  7.5133e-03, -1.8384e-01, -3.8965e-02, -1.7766e-01,
                      -2.1348e-02, -2.0718e-01,  6.6428e-02, -7.0877e-02, -1.1955e-01,
                       8.2285e-02,  1.9477e-02, -2.5003e-02, -1.4468e-01,  1.7946e-01,
                       6.6041e-02,  2.8231e-02,  1.6399e-01, -9.4300e-02,  1.3085e-01,
                       1.4066e-02,  1.1889e-01, -1.5489e-01, -4.1116e-02, -1.1144e-02,
                       5.8016e-02, -1.5430e-01,  9.2477e-02, -4.7090e-02, -4.5951e-02,
                       2.5903e-02,  1.0875e-01, -3.2437e-03, -1.1544e-01,  7.6236e-02,
                      -7.8145e-02, -5.9642e-02,  6.0688e-02, -3.2751e-01, -1.0837e-01,
                      -4.1229e-02, -2.5047e-01,  4.6723e-02, -1.4570e-01, -1.0011e-01,
                       2.0646e-01,  1.2510e-01,  6.3165e-02,  9.6769e-02, -5.2077e-02,
                       7.0515e-02, -5.1901e-02,  8.9442e-02, -1.2134e-01,  3.6018e-02,
                       4.4655e-02, -2.8788e-02, -3.9227e-02,  9.6426e-02, -3.8297e-01,
                       2.1033e-01, -3.6272e-02,  2.7055e-01, -1.8653e-02,  1.7402e-02,
                      -8.3565e-02, -2.5585e-01,  1.7288e-01,  7.8483e-02,  1.5699e-01,
                       5.2158e-02, -4.7253e-03, -1.9652e-01, -1.5391e-01, -1.5225e-01,
                      -1.0895e-01,  1.0510e-01, -3.7223e-02,  1.9506e-01, -8.4480e-02,
                       3.3327e-02, -2.6987e-01,  1.8088e-01,  1.6480e-01, -1.1712e-01,
                       6.8231e-02,  7.1807e-02,  6.0608e-02,  1.2583e-01,  1.4426e-01,
                       6.8424e-02, -3.6560e-01,  1.4057e-01,  2.2118e-02,  1.6074e-01,
                      -1.2411e-01, -6.3768e-03,  5.5279e-02, -8.6790e-02,  1.2425e-01,
                      -1.8716e-01,  2.2280e-01,  1.4061e-01,  7.8957e-02,  2.9717e-02,
                      -9.8470e-02,  2.0397e-02,  5.5148e-02, -1.6767e-01, -1.6038e-01,
                       7.4362e-02,  8.8352e-02,  1.1760e-01,  2.4527e-02,  2.3122e-01,
                       4.2277e-02, -2.4659e-01,  1.4459e-03,  2.6857e-01,  1.2097e-01,
                       9.4365e-02, -8.8296e-02,  1.7285e-01, -1.2952e-02,  6.9976e-02,
                       2.4042e-01,  5.2952e-02,  7.0908e-02,  8.6692e-02, -5.3602e-02,
                      -2.3285e-02,  1.2535e-01, -1.9637e-02, -1.5155e-01,  1.6761e-01,
                      -2.9230e-02, -2.8782e-03,  8.9619e-02,  2.3629e-02, -6.0869e-02,
                      -7.1185e-02,  2.6276e-02, -5.9353e-02,  1.7245e-01, -9.4571e-02,
                       6.2425e-02,  3.3974e-02, -9.6658e-02,  1.6621e-01,  5.1490e-02,
                       8.2049e-02, -1.0243e-01,  1.6111e-02, -1.6845e-01, -4.4380e-02,
                       5.5852e-02,  6.8571e-02,  1.6976e-01, -6.5396e-02,  1.7085e-01,
                       1.7114e-01,  2.1300e-01, -8.4574e-03,  1.8087e-01,  1.4193e-01,
                      -7.5187e-02,  2.3297e-05, -9.9859e-05,  1.5445e-04, -6.2449e-05,
                       7.2580e-05, -8.7034e-05, -2.8952e-05,  4.8017e-05,  4.8538e-05,
                       4.2522e-05,  3.9595e-05, -1.5417e-04, -1.9314e-05,  2.4255e-05,
                      -4.2147e-05,  8.3067e-05, -6.0661e-05,  6.1676e-05, -1.4559e-04,
                       1.5981e-04, -3.8827e-05, -5.3849e-05,  2.5643e-06,  3.3424e-05,
                      -2.7575e-05,  2.6600e-06,  8.1566e-05, -2.3981e-05, -9.2065e-05,
                       7.3537e-05,  6.2040e-05, -1.0057e-04, -1.8067e-06,  7.9013e-05,
                      -4.8911e-05, -2.0978e-05, -9.1020e-06, -5.9614e-05, -6.9011e-06,
                      -2.0666e-04,  1.7412e-04,  1.0537e-04, -6.3108e-06, -7.8770e-05,
                      -3.0233e-05,  4.1574e-05,  6.2274e-05, -1.6065e-04, -5.0310e-06,
                       3.0585e-05,  1.0674e-04,  6.3969e-05,  2.5368e-05, -4.1280e-06,
                      -1.5823e-04, -2.0419e-05, -1.5309e-05,  1.2127e-04, -3.5520e-05,
                       3.8001e-05, -2.0576e-06,  2.2629e-05, -3.0141e-05, -7.0873e-05,
                      -7.5094e-05,  3.3664e-05,  1.4800e-05,  1.0638e-04, -5.8768e-05,
                      -1.5223e-04,  1.5719e-05,  5.8617e-05,  2.1977e-05,  2.1677e-06,
                      -4.0169e-05,  8.8567e-05, -3.1258e-05,  1.5294e-05,  7.0415e-05,
                      -9.2942e-07, -2.7400e-05,  1.0962e-04,  8.6501e-05,  1.5616e-05,
                       3.9266e-05, -1.8700e-06, -9.7488e-05,  1.8723e-04, -4.3931e-05,
                      -3.4443e-05,  3.4064e-05, -1.2474e-05, -1.2908e-04,  3.2244e-05,
                       3.0548e-06, -1.6126e-04,  1.3388e-04, -3.9831e-05, -7.3271e-05,
                       1.7937e-04, -1.5357e-05,  2.4118e-06,  3.2233e-05,  2.2574e-05,
                       4.2599e-05, -3.8762e-05, -1.2728e-04, -3.1928e-05, -3.6668e-05,
                      -5.8203e-05,  9.0895e-05,  4.5065e-05, -3.1702e-05,  7.4889e-05,
                      -8.6129e-05, -1.5091e-05,  2.8992e-05, -5.7598e-06,  3.9524e-05,
                      -1.6429e-05, -5.0750e-05, -1.8778e-05,  4.2223e-06,  9.4492e-05,
                      -8.7453e-05,  9.5681e-05,  9.8238e-05,  7.7146e-05,  6.7159e-05,
                       6.3502e-05, -8.7480e-06, -2.9391e-05, -1.5562e-04,  1.4021e-04,
                      -6.9251e-05, -7.9162e-05,  5.1257e-06, -1.2182e-05, -8.8099e-05,
                      -1.9502e-05,  3.0237e-05, -1.0960e-04,  2.1019e-04,  9.0947e-05,
                      -5.9847e-05, -1.2173e-04, -7.1089e-06,  3.8846e-05, -6.4020e-05,
                       1.6518e-05,  3.7573e-05,  8.4671e-05, -1.3243e-04, -1.3113e-04,
                       6.6820e-05,  8.5061e-06,  8.3566e-05,  1.4205e-04,  6.7049e-05,
                       3.9261e-05,  2.8887e-05,  1.7865e-05, -6.0121e-06, -3.3822e-05,
                      -6.7989e-05, -3.2339e-05,  1.9307e-06, -1.2923e-04, -7.5886e-05,
                      -1.5592e-05, -1.7040e-05,  1.7118e-04, -2.6473e-05,  1.6393e-04,
                       1.1859e-06, -2.0758e-05,  4.6217e-05,  5.9667e-05,  5.5728e-05,
                       5.2350e-05,  2.8777e-05, -1.2013e-05, -1.3730e-04,  1.2221e-04,
                      -7.0274e-05,  2.7464e-05,  9.6674e-06,  2.6345e-05, -9.8885e-05,
                      -1.1301e-04, -2.5515e-05, -7.6560e-05, -1.1869e-04,  5.2363e-05,
                       1.4886e-05,  5.4603e-05, -5.6919e-06, -5.4044e-05, -1.6283e-05,
                       1.3170e-04, -1.0557e-04, -2.3929e-05,  1.7495e-04, -6.5930e-05,
                      -1.6587e-05, -1.2393e-04,  1.0113e-05, -2.5379e-05,  3.7191e-06,
                       1.4755e-04, -1.5596e-05,  1.6492e-05, -5.8744e-05, -1.2369e-04,
                      -1.8416e-05, -6.0062e-05, -4.3124e-05, -2.8308e-05,  9.6610e-05,
                      -6.5549e-05, -1.2135e-04,  9.3090e-05,  1.4167e-04,  1.6291e-05,
                       1.8197e-05,  5.3791e-05, -8.9541e-05, -2.9516e-05,  3.2087e-05,
                       6.6578e-05,  1.2900e-04, -4.6354e-05, -9.0688e-05, -1.3036e-04,
                       1.0472e-04,  9.0376e-05, -8.5256e-05,  1.4133e-04, -1.0362e-04,
                      -6.5638e-05, -3.2428e-05, -1.6039e-05,  7.2516e-05,  3.3883e-05,
                       2.7182e-05,  1.9766e-05,  4.1189e-06, -1.8008e-05, -1.4589e-04,
                       6.3808e-05,  1.4216e-04,  4.0054e-05,  8.4648e-06,  7.5112e-06,
                       4.2055e-05, -4.1909e-05, -1.9620e-02,  2.2821e-02, -5.9178e-02,
                       1.1136e-01, -2.6963e-02,  3.4806e-03, -2.3240e-02,  8.2393e-02,
                      -7.8794e-02, -1.2979e-02, -5.6885e-02, -3.1615e-02, -3.4414e-02,
                       7.1995e-02,  3.8072e-04,  3.8823e-02,  2.4930e-02, -1.2184e-01,
                       4.3951e-02,  4.4713e-03, -6.8090e-02, -7.8901e-02, -7.5399e-02,
                       6.5718e-03,  6.8263e-03, -2.4265e-02, -9.0608e-02, -3.6161e-02,
                      -4.5225e-02, -7.4201e-02, -3.9362e-02,  1.2965e-02,  5.5981e-02,
                      -8.4990e-02, -2.8915e-02, -1.6446e-02, -5.3359e-02,  4.4870e-02,
                       3.3111e-02, -6.1977e-02, -1.0785e-01,  5.3130e-03, -2.9047e-02,
                      -7.7593e-02,  2.1266e-02,  1.3932e-02,  4.4028e-02, -2.7190e-03,
                      -3.2514e-03,  8.9403e-03,  7.8265e-02,  4.3603e-02, -6.2694e-02,
                       1.1420e-01,  3.2841e-02,  1.2464e-02, -2.7204e-02, -6.7046e-02,
                       7.6345e-02, -2.0509e-02,  8.3450e-02,  3.4723e-02, -1.9027e-02,
                       4.3572e-02, -5.4079e-02,  3.9466e-02,  4.0653e-02,  1.1909e-01,
                       2.6757e-03, -7.7366e-02,  4.6955e-02, -9.9793e-02,  1.1687e-02,
                      -8.0428e-02, -2.6753e-02,  1.3679e-01,  1.6078e-02,  2.7491e-02,
                       1.3475e-02, -1.5424e-02,  5.3991e-02, -7.3312e-02, -1.9900e-02,
                       8.1849e-02, -1.6306e-02,  8.7072e-03, -1.4120e-02, -7.0064e-02,
                      -3.9838e-02, -5.7975e-02,  5.2260e-02,  3.1655e-02,  5.0774e-02,
                      -1.8694e-02, -6.6119e-02,  2.1104e-02,  5.3867e-02,  5.2951e-02,
                       2.3795e-02,  5.5906e-02,  5.8133e-04, -9.0869e-02, -6.6733e-02,
                      -1.0359e-01, -9.0768e-02,  1.3703e-02, -3.7386e-02,  8.4560e-02,
                      -9.7491e-02,  2.4321e-02, -3.7358e-02,  6.4909e-02,  3.5712e-02,
                       3.4588e-02, -1.2667e-02, -5.2466e-02,  2.6531e-02, -3.3223e-02,
                       1.1681e-02,  1.2268e-01, -3.1269e-02, -5.6970e-04, -2.8038e-02,
                      -3.9526e-02, -4.9130e-02, -7.8550e-03, -2.9122e-02, -5.5762e-02,
                      -2.8771e-03,  7.8072e-03, -5.5797e-02, -4.6947e-02,  6.3587e-02,
                      -4.0360e-02, -4.6541e-02,  1.0773e-01,  4.4696e-02, -7.3606e-02,
                      -3.4312e-02,  9.0236e-03, -1.2680e-01,  5.5229e-02, -5.6996e-02,
                      -1.0262e-02, -1.0607e-01, -5.6076e-03, -9.3149e-02,  7.8357e-02,
                       5.9163e-02, -3.2884e-02,  5.0766e-02, -4.7096e-03,  4.6144e-02,
                       3.9209e-02, -2.0089e-03,  8.3174e-02,  6.3626e-04, -2.9643e-02,
                      -2.1792e-02,  5.5653e-03, -4.3155e-02, -5.3795e-02, -3.8884e-02,
                       1.8212e-02,  8.2759e-02,  1.1959e-01, -2.6254e-03, -1.4701e-03,
                      -3.0351e-03, -2.9818e-02, -1.2298e-01, -6.8112e-02,  6.8170e-02,
                       3.9695e-02, -1.1358e-02,  2.2536e-02, -4.3417e-02, -6.3989e-02,
                       3.6228e-02, -2.3690e-02,  4.3655e-02, -2.0143e-02,  6.8125e-02,
                      -7.6964e-02, -7.8195e-02, -5.5758e-03, -9.6036e-02,  6.5469e-02,
                       7.0229e-02,  4.0930e-02, -1.7226e-02, -3.9139e-02,  4.4687e-02,
                       2.8134e-02, -2.2233e-02, -6.3199e-02,  6.7941e-03,  2.5600e-02,
                       2.1537e-02,  5.4773e-02,  4.0085e-02,  4.1503e-03,  6.8422e-02,
                      -5.6793e-03,  3.4348e-02, -8.0634e-03,  1.2685e-01,  2.7375e-02,
                      -2.0565e-02,  9.2634e-02, -1.0685e-01,  2.4965e-03, -2.5811e-02,
                       1.6992e-02,  6.1862e-02, -4.3866e-02, -3.1789e-03, -1.7862e-02,
                      -8.0865e-02, -1.8768e-02,  5.9707e-03,  4.6281e-02, -1.1403e-02,
                      -8.1978e-03,  2.7390e-03,  8.2202e-02,  5.2634e-02, -5.7383e-02,
                       4.8931e-02,  5.3120e-02, -8.6017e-02,  1.2564e-02,  3.4459e-02,
                      -1.0927e-01,  7.0169e-02,  8.8354e-02,  7.0687e-02,  4.7397e-02,
                      -2.6737e-02, -6.5784e-02,  8.1546e-02, -1.0852e-01,  5.2288e-03,
                      -1.2229e-03,  6.1654e-02, -7.4271e-03, -1.1321e-01,  2.5430e-03,
                       1.0704e-01,  5.6551e-02, -4.5932e-02,  4.1223e-02,  8.8182e-02,
                       5.2187e-02,  3.7069e-03, -6.3054e-02])),
             ('transformer_encoder.layers.0.self_attn.out_proj.weight',
              tensor([[ 0.0236, -0.0367,  0.0273,  ..., -0.0622,  0.0828, -0.0737],
                      [ 0.1898, -0.0233, -0.0207,  ..., -0.0537, -0.0517, -0.0112],
                      [ 0.0342, -0.1297,  0.0636,  ..., -0.0118,  0.0448, -0.0129],
                      ...,
                      [-0.1462, -0.0221, -0.0243,  ..., -0.1800, -0.0147,  0.0410],
                      [ 0.1124,  0.0812, -0.0550,  ...,  0.0180,  0.0322,  0.1443],
                      [ 0.0034, -0.1404,  0.0290,  ...,  0.1786,  0.0656,  0.0869]])),
             ('transformer_encoder.layers.0.self_attn.out_proj.bias',
              tensor([ 0.0581,  0.2009, -0.1252,  0.1416,  0.1152, -0.0142, -0.0244, -0.0956,
                      -0.0634,  0.0928, -0.1092,  0.1491, -0.0020,  0.0997, -0.1203, -0.1177,
                       0.1722, -0.0559,  0.0780, -0.1210,  0.0698, -0.1185,  0.1918,  0.0375,
                       0.0661, -0.0157, -0.0195, -0.1001, -0.0032, -0.0564,  0.1233,  0.1508,
                       0.0019,  0.0399,  0.1488,  0.1133, -0.1018, -0.0153,  0.0233, -0.0591,
                       0.0087, -0.1264,  0.1095, -0.0862,  0.0788,  0.0321, -0.2745,  0.0748,
                      -0.0159,  0.1531, -0.0304, -0.0154,  0.2528,  0.2235,  0.1777,  0.0839,
                      -0.0213,  0.0358, -0.0216,  0.1274,  0.0406,  0.0768, -0.0674,  0.0816,
                      -0.0332,  0.0606,  0.0230,  0.0303, -0.1895,  0.0712,  0.0565,  0.1426,
                      -0.0853, -0.0452,  0.0325, -0.1409, -0.0443,  0.0557, -0.0504,  0.0214,
                      -0.0297,  0.0649, -0.0394, -0.0035,  0.0188, -0.0635,  0.0019, -0.0673,
                       0.0771, -0.0305, -0.0940,  0.0563,  0.0113, -0.0951,  0.0378,  0.2036,
                      -0.0757,  0.0444, -0.1540, -0.0641,  0.1425,  0.1083,  0.1391,  0.0665,
                      -0.0822,  0.0136,  0.0363,  0.0098, -0.0453,  0.1306,  0.0444,  0.0039,
                      -0.3224,  0.1834,  0.0607, -0.1058, -0.1239, -0.1354,  0.2077, -0.0916,
                      -0.0308, -0.0720,  0.1064, -0.0643, -0.0239, -0.1389, -0.1041, -0.1285,
                      -0.1113,  0.0542,  0.0908,  0.1770, -0.0142, -0.1073,  0.1750, -0.1266,
                      -0.0056, -0.0172, -0.0056,  0.1525,  0.0117,  0.2017, -0.0767, -0.1311,
                      -0.0460,  0.1334,  0.1092,  0.0037, -0.2505, -0.0498, -0.1880, -0.0849,
                       0.0843, -0.0500, -0.0050,  0.0546, -0.0477, -0.0154,  0.1698, -0.1324,
                       0.1687,  0.1328, -0.0468,  0.0555, -0.0031, -0.0623, -0.2934,  0.0959,
                       0.1736, -0.0810,  0.1054, -0.1191, -0.0545,  0.0631, -0.1322, -0.0451,
                      -0.0334, -0.1192,  0.0440,  0.0163, -0.0287,  0.0029,  0.0924, -0.0741,
                       0.0946, -0.0094, -0.0275,  0.1415,  0.0842,  0.0133,  0.0475,  0.0044,
                      -0.0374,  0.1817,  0.0577, -0.0140, -0.0118,  0.0224, -0.1220, -0.0606,
                       0.1363, -0.0122, -0.0781, -0.0256,  0.0214, -0.0244, -0.0871, -0.0900,
                      -0.0764,  0.0782, -0.0852, -0.0880, -0.0782,  0.0610, -0.0960,  0.0905,
                      -0.0526,  0.1156, -0.0311,  0.1005, -0.0465, -0.0480,  0.2041,  0.0832,
                      -0.0681, -0.5865,  0.0788, -0.0429,  0.0465, -0.0784, -0.0029, -0.1357,
                      -0.0306, -0.0025, -0.2361, -0.2243, -0.1428,  0.1414,  0.0586, -0.0598,
                      -0.0181, -0.1679, -0.1402, -0.1802, -0.1877,  0.0605, -0.1203,  0.0360,
                      -0.0624,  0.0049,  0.0062,  0.0154,  0.1040,  0.1243, -0.0023,  0.0927])),
             ('transformer_encoder.layers.0.linear1.weight',
              tensor([[-0.0886,  0.0186,  0.1550,  ..., -0.0235, -0.0918, -0.0467],
                      [-0.0494, -0.0749,  0.3088,  ...,  0.3958, -0.2187, -0.0189],
                      [-0.1661,  0.0355,  0.0171,  ..., -0.0695, -0.1012,  0.1139],
                      ...,
                      [-0.0280, -0.0124, -0.0246,  ...,  0.0538,  0.0303, -0.0305],
                      [ 0.0638, -0.3168,  0.0334,  ...,  0.1467,  0.0930, -0.2618],
                      [-0.0482, -0.2649,  0.0152,  ..., -0.1776, -0.0060,  0.1323]])),
             ('transformer_encoder.layers.0.linear1.bias',
              tensor([-0.1720, -0.1802, -0.1611,  ..., -0.1529, -0.1458, -0.2070])),
             ('transformer_encoder.layers.0.linear2.weight',